### ISSUE TITLE
run 'npm start' got exception

### ISSUE THREAD

**Issue by xsgkaka** [fbsamples/f8app#10]
these are my versions
node: v5.10.1
npm: v3.8.6
os: win 7 x64

when i run 'npm start', i got these errors.

`E:\workspace\ReactWorkspace\f8app\node_modules\.npminstall\react-native\0.23.1\r
eact-native\Libraries\react-native\react-native.js:120
  ...require('React'),
  ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\workspace\Rea
ctWorkspace\f8app\node_modules\.npminstall\babel-register\6.7.2\babel-register\l
ib\node.js:134:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at E:\workspace\ReactWorkspace\f8app\node_modules\.npminstall\babel-core\6.7
.6\babel-core\lib\transformation\file\options\option-manager.js:368:22
    at Array.map (native)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xsg\\AppData\\Ro
aming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! F8v2@0.0.1 start: `babel-node ./server/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the F8v2@0.0.1 start script 'babel-node ./server/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the F8v2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./server/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs F8v2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls F8v2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\workspace\ReactWorkspace\f8app\npm-debug.log`

i can not find the solution, can anyone help me? thanks in advance

**Comment by frantic** [comment]
Try removing the `node_modules` folder completely and re-running `npm install`. From the path it seems like we might be grabbing incorrect file. Please reopen if this doesn't help.

**Comment by xsgkaka** [comment]
i remove the node_modules and clean the /user/xxx/appdata/local/temp floder .then re-running the npm install command .then i got the same error .
i think the vs is not be installed correct.so i re-install the vs express 2013.and according to the node-gyp install guid.
now i remove the node-moudles floder and clean  the temp floder .and re-running the npm install.but i got this error:`AttributeError: 'MSVSProject' object has no attribute 'iteritems'`. i google this error. i have no idea to solve this expection. now i almost lost my mind. so this " AttributeError: 'MSVSProject' object has no attribute 'iteritems " exception can be solved?

**Comment by xsgkaka** [comment]
now i have solve the problem . i use the "npm ls" command to show the deps,i fond some deps no be correctly installed, i intall them alone. now i fix it. ^_^
