### ISSUE TITLE
How to set backgroundImage in ListContainer dynamically

### ISSUE THREAD

**Issue by zh-wowtv** [fbsamples/f8app#100]
Here is my code:

```
     <View style={styles.container}>
        <ListContainer
          title="Message"
          backgroundImage={backImage}
          leftItem={leftItem}
          rightItem={rightItem}>
          {this.renderContent()}
        </ListContainer>
      </View>
```

It's fine if the backImage is ```require('./img/newpost-background.png');```. But how am I supposed to set the backImage dynacmically if I know the file url of the image?

**Comment by zh-wowtv** [comment]
Based on the source code of ```resolveAssetSource``` and unit test. If the paramter passed to ```backgroundImage``` is a object, the ```resolveAssetSource``` will return the object directly.  Then I changed the source code of ```ListContainer``` and ```ParallaxBackground```. I changed the ```backgroundImage``` from ```number``` to ```any```. But when I run the following code:

    ```
const backImage = this.state.coverImage === null ? require('./img/newpost-background.png') : this.state.coverImage;
    console.log(backImage);    

    // original method    
    return (      
      <View style={styles.container}>
        <ListContainer
          title="New Message"
          backgroundImage={backImage}
          leftItem={leftItem}
          rightItem={rightItem}>
          <PureListView
            enableEmptySections = {true}
            renderEmptyList={this.renderContent} 
            renderRow={this.renderRow}/>          
        </ListContainer>
      </View>
    )
```

I got the following error message:

> "JSON value '<null>' of type NSNull cannot be converted to NSNumber"

Any idea ? Thanks.

**Comment by frantic** [comment]
You could use `{url: 'http://....', width: 100, height: 100}` as the source. It should work but will not typecheck because I hardcoded `number` as the only allowed type (can be fixed too by replacing `number` in props with `number | {url: string, width: number, height: number}`
