### ISSUE TITLE
Tutorial on F8App Awesome UX

### ISSUE THREAD

**Issue by bondanherumurti** [fbsamples/f8app#104]
Hi guys, pardon me if the question is not that advance

Im really interesting on the UX header parallax, SegmentControl that able to stick below header and swipeable schedule list (Day 1, Day 2)... It will accel new devs react native to understand advance UX on react native

Thank you very much

Bondan H

**Comment by bondanherumurti** [comment]
Sorry the question wasnt complete, so if you guys could publish step by step on creating the UI that would help react native starter

**Comment by frantic** [comment]
Hey Bondan, thanks for the idea! I've added it to my topics list. It was a fun exercise to build that component, and I think I rewrote it at least 3 times before arriving at the final design, so there will be some interesting stuff to discuss.

**Comment by eladgel** [comment]
any new on this subject? I'm working real hard on decoupling the data handling from the view elements
