### ISSUE TITLE
Node-gyp rebuild not working on windows

### ISSUE THREAD

**Issue by prashantalhat** [fbsamples/f8app#105]
I have tried this many times but npm install is not successful on windows. Is someone else facing this issue?

`npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bufferutil
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.`

How to fix this issue?

**Comment by frantic** [comment]
@prashantalhat I used OSX to develop the app and not sure if I can help with this problem. Maybe try filing an issue against `bufferutil` package?

**Comment by nealsun** [comment]
I got same error with OSX 10.12
