### ISSUE TITLE
Cannot evaluate module react-native-fbsdk : Configuration with name ‘default’ not found

### ISSUE THREAD

**Issue by kimown** [fbsamples/f8app#109]
OS: ubuntu 14.04
![err](https://cloud.githubusercontent.com/assets/7932380/17461444/2f52e56c-5cbf-11e6-93af-005e3dc9690a.png)

And I found the issue associated with the problem,https://github.com/facebook/react-native-fbsdk/issues/205

The module path  in the settings.gradle ,should be 'android' instead of 'Android'.
https://github.com/fbsamples/f8app/blob/master/android/settings.gradle#L13

**Comment by Dssdiego** [comment]
Thanks! It helped me!

**Comment by pasystem** [comment]
Thanks!
