### ISSUE TITLE
npm ERR! code EBADPLATFORM

### ISSUE THREAD

**Issue by thisdotvicky** [fbsamples/f8app#117]
> utf-8-validate@1.2.1 install /home/vimal/vimal/f8app/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/home/vimal/vimal/f8app/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory`/home/vimal/vimal/f8app/node_modules/utf-8-validate/build'
npm WARN prefer global marked@0.3.5 should be installed with -g

> bufferutil@1.2.1 install /home/vimal/vimal/f8app/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/home/vimal/vimal/f8app/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory`/home/vimal/vimal/f8app/node_modules/bufferutil/build'

> spawn-sync@1.0.15 postinstall /home/vimal/vimal/f8app/node_modules/spawn-sync
> node postinstall

npm ERR! Linux 3.19.0-65-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vimal/vimal/f8app/npm-debug.log
vimal@vimal-VPCEB1AGG:~/vimal/f8app$ sudo npm install
[sudo] password for vimal: 
npm ERR! Linux 3.19.0-65-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vimal/vimal/f8app/npm-debug.log

**Comment by hramos** [comment]
I was able to get around this by using node v6.5.0.

**Comment by Abubaker87** [comment]
I am also getting this error. I have the node v6.7.0 and npm v3.10.9. What is the solution?

**Comment by Opelar** [comment]
C:\Users\my
λ npm -g update
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@2.1.7: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\my\AppData\Roaming\npm-cache\_logs\2017-08-09T10_07_19_031Z-debug.log

λ node -v
v8.2.1

λ npm -v
5.3.0



I also getting this error
