### ISSUE TITLE
Choosing Filters for Events leads to Red Screen of Death and Error: undefined is not an object (evaluating 'AppEventsLogger.logEvent') 

### ISSUE THREAD

**Issue by msutyak** [fbsamples/f8app#119]
When choosing Filters under Events, and clicking Apply Filter, I get the error:

undefined is not an object (evaluating 'AppEventsLogger.logEvent') 

Running iOS simulator, Mac OS X machine.  

<img width="374" alt="screen shot 2016-09-08 at 9 17 06 pm" src="https://cloud.githubusercontent.com/assets/3487153/18375282/a612ebda-7609-11e6-9635-bb6b531707b1.png">

**Comment by timcamber** [comment]
I'm seeing this issue when I try to dismiss the login screen at first app launch.

**Comment by marciobueno1** [comment]
Same here... I am running on MacOS Simulator.

**Comment by gaykov** [comment]
Take a look at https://github.com/fbsamples/f8app/issues/106#issuecomment-244823561. You can comment other logEvent calls in this file and It should helps you
