### ISSUE TITLE
 npm run import-data error

### ISSUE THREAD

**Issue by veryitman** [fbsamples/f8app#122]
npm run import-data

> F8v2@0.0.1 import-data /Users/mark/workspace/mzProjs/ReactNative/Exts/f8app
> babel-node ./scripts/import-data-from-parse.js

Loading Speakers
Cleaning old Speakers data
ParseError { code: 1, message: undefined }

**Comment by StuartAshby** [comment]
@veryitman Did you make sure the local Parse server was running via 'npm start' first?

**Comment by veryitman** [comment]
@StuartAshby yes i do.

**Comment by gondar00** [comment]
@veryitman did you check that mongoDB is running 
`lsof -iTCP:27017 -sTCP:LISTEN`

**OR** 

 if you are using an external MongoDB server did you set DATABASE_URI:
`export DATABASE_URI=mongodb://example-mongo-hosting.com:1337/my-awesome-database`

**Comment by grifotv** [comment]
@veryitman here's the fix https://github.com/fbsamples/f8app/issues/48#issuecomment-219549698

**Comment by veryitman** [comment]
@grifotv Thank you.
But i get new error. I'm crazy as soon.
I post the problem at [#48 (comment)](https://github.com/fbsamples/f8app/issues/48#issuecomment-219549698)

**Comment by tomoima525** [comment]
@veryitman 
I guess you are not running mongoDB

try
```
$ brew services start mongodb
==> Tapping homebrew/services
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services'...
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 10 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
Checking connectivity... done.
Tapped 0 formulae (36 files, 47K)
==> Successfully started `mongodb` (label: homebrew.mxcl.mongodb)
```

Then you get a result of lsof

```
$ lsof -iTCP:27017 -sTCP:LISTEN
COMMAND   PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
mongod  66871 tomoaki    7u  IPv4 0xed72c836bdf0ebb1      0t0  TCP localhost:27017 (LISTEN)
```

Then it should work

**Comment by woshi82** [comment]
i make a mistake to  run `export DATABASE_URI=mongodb://example-mongo-hosting.com:1337/my-awesome-database
` ,which don't need it at all.and now i don't know how to cancel the `DATABASE_URI` settings。
when i run `npm run import-data`,appeared the same error, even i have restart the `mongdb`。
I don't know what can i do next。 anybody can help me ?

**Comment by veryitman** [comment]
@grifotv Thank you very much.

**Comment by veryitman** [comment]
@gondar00 Thanks all the same.
#48  is right.
