### ISSUE TITLE
Build Fail -- Ensure that the application's Info.plist contains a value for CFBundleIdentifier.

### ISSUE THREAD

**Issue by hhashmi** [fbsamples/f8app#123]
1 - sudo npm install  -- successful
2 - mongodb already installed
3 - nam run -- successful (parse server working, graphQL server working)
4 - react-native run-ios --- build fail 

following are the logs

Found Xcode project F8v2.xcodeproj
Launching iPhone 6 (10.0)...
Building using "xcodebuild -project F8v2.xcodeproj -scheme F8v2 -destination id=6EC2F15A-0B90-4098-B788-18D8C8F02780 -derivedDataPath build"
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/Hassan/Documents/f8app-master/ios/build

=== BUILD TARGET BVLinearGradient OF PROJECT BVLinearGradient WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET F8v2 OF PROJECT F8v2 WITH CONFIGURATION Debug ===

Check dependencies
The file “Pods-F8v2.debug.xcconfig” couldn’t be opened because there is no such file. (/Users/Hassan/Documents/f8app-master/ios/Pods/Target Support Files/Pods-F8v2/Pods-F8v2.debug.xcconfig)

PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock build/Build/Intermediates/F8v2.build/Debug-iphonesimulator/F8v2.build/Script-BE0B165BA96102DAE4AF6D67.sh
    cd /Users/Hassan/Documents/f8app-master/ios
    /bin/sh -c /Users/Hassan/Documents/f8app-master/ios/build/Build/Intermediates/F8v2.build/Debug-iphonesimulator/F8v2.build/Script-BE0B165BA96102DAE4AF6D67.sh
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

*\* BUILD FAILED **

The following build commands failed:
    PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock build/Build/Intermediates/F8v2.build/Debug-iphonesimulator/F8v2.build/Script-BE0B165BA96102DAE4AF6D67.sh
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/F8v2.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/Hassan/Documents/f8app-master/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/F8v2.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

```
at checkExecSyncError (child_process.js:483:13)
at Object.execFileSync (child_process.js:503:13)
at _runIOS (/Users/Hassan/Documents/f8app-master/node_modules/react-native/local-cli/runIOS/runIOS.js:82:32)
at /Users/Hassan/Documents/f8app-master/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5
at tryCallTwo (/Users/Hassan/Documents/f8app-master/node_modules/react-native/node_modules/promise/lib/core.js:45:5)
at doResolve (/Users/Hassan/Documents/f8app-master/node_modules/react-native/node_modules/promise/lib/core.js:200:13)
at new Promise (/Users/Hassan/Documents/f8app-master/node_modules/react-native/node_modules/promise/lib/core.js:66:3)
at Array.runIOS (/Users/Hassan/Documents/f8app-master/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
at Object.run (/Users/Hassan/Documents/f8app-master/node_modules/react-native/local-cli/cliEntry.js:96:13)
at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7) 
```

**Comment by StuartAshby** [comment]
Same problem here. Do you have Xcode 8.0? I am going to uninstall Xcode 8.0 and install Xcode 7.3.1 and try again.

**Comment by StuartAshby** [comment]
I got it running with Xcode 7.3.1.

**Comment by hhashmi** [comment]
I;m new to mac.

I have installed Xcode 8.0
OS X 10.11.5

how to downgrade it to Xcode 7.3.1.

**Comment by StuartAshby** [comment]
@hhashmi you have to completely uninstall and reinstall the beast that is Xcode.

**Comment by Forever-Austin** [comment]
Can I run it successful using Xcode 7 ?

**Comment by phpsmarter** [comment]
same error code . All other install is correct,but cannot  compile successful.

The following build commands failed:
	CompileC /Users/apple/Desktop/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTScrollView.o /Users/apple/Desktop/f8app/node_modules/react-native/React/Views/RCTScrollView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/F8v2.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/apple/Desktop/f8app/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/F8v2.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:465:13)
    at Object.execFileSync (child_process.js:485:13)
    at _runIOS (/Users/apple/Desktop/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:82:32)
    at /Users/apple/Desktop/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5
    at tryCallTwo (/Users/apple/Desktop/f8app/node_modules/react-native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/apple/Desktop/f8app/node_modules/react-native/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/apple/Desktop/f8app/node_modules/react-native/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/apple/Desktop/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
    at Object.run (/Users/apple/Desktop/f8app/node_modules/react-native/local-cli/cliEntry.js:96:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)

**Comment by Jay-Li-AU** [comment]
same as #124, have a look at the solution

**Comment by WillSquire** [comment]
The issue for me was a space in `build/info.plist`'s directory path.
Removing a space in a parent folder solved it.

**Comment by Prosquid1** [comment]
Solved immediately by Linking Library in Xcode Project

Targets > Linked Frameworks and Libraries > libBLVLinearGradient.a

**Comment by henryawang** [comment]
<img width="542" alt="截屏2019-10-1323 05 01" src="https://user-images.githubusercontent.com/50544647/66717653-f2fa8280-ee0d-11e9-9022-c1530c1b15e0.png">
1. open info.plist
2.rename  bundle identifier

**Comment by Prabhneet-Web** [comment]
This happens if the GoogleService-Info.plist is missing.
