### ISSUE TITLE
iOS version is not working.

### ISSUE THREAD

**Issue by TianDaGe** [fbsamples/f8app#124]
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Volumes/D/Workstation/ReactNative/f8app/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/F8v2.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

In the XCode, if I build then I get such these 2 errors.

RCTWebSocket 2 issues

---
## SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);

/Volumes/D/Workstation/ReactNative/f8app/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:494:3: Ignoring return value of function declared with warn_unused_result attribute

---
## SecRandomCopyBytes(kSecRandomDefault, sizeof(uint32_t), (uint8_t *)mask_key);

/Volumes/D/Workstation/ReactNative/f8app/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:1334:5: Ignoring return value of function declared with warn_unused_result attribute
- XCode 8.0
- Mac OS X EI Captain
- Node v6.4
- npm v3.10.7

I check this issue in the previous closed issues. but currently it is not working on my side.
How can I do?

**Comment by TianDaGe** [comment]
I removed XCode 8.0 and reinstall XCode7.3.1, then building is okay.

**Comment by CrewHack** [comment]
@TianDaGe I am getting build errors for the iOS app. I am going to try uninstalling Xcode 8 and installing 7.3.1 as you suggest. Please tell me, is your react-native version 0.28?

**Comment by TianDaGe** [comment]
Yes, version is 0.28.
The building was okay. But it is not working in the simulator again.
Error message is "Native module cannot be null.".

**Comment by StuartAshby** [comment]
@TianDaGe  I am getting build errors for the iOS app. I am going to try uninstalling Xcode 8 and installing 7.3.1 as you suggest. Please tell me, is your react-native version 0.28?

**Comment by TianDaGe** [comment]
Yes, version is 0.28.
The building was okay. But it is not working in the simulator again.
Error message is "Native module cannot be null.".

**Comment by StuartAshby** [comment]
I got that same error, but was able to fix it by first making sure I had Xcode 7.3.1 installed and then starting all over from scratch from the instructions here https://github.com/fbsamples/f8app/blob/master/README.md. I've got the app opening in the iOS Simulator now.

**Comment by TianDaGe** [comment]
When react-native-fsdk will be suitable with XCode8 and iOS10.0.1?

**Comment by gavinxyang** [comment]
Same question here.

**Comment by jiazil** [comment]
Same question for me.

**Comment by Jay-Li-AU** [comment]
For build error, if using xcode8, open F8v2.xcworkspace in xcode, then you will find some _refreshControl errors. Change _refreshControl to refreshControl, then the build will pass.

For Native module be null, ...undefined...issues, please check out [https://github.com/fbsamples/f8app/issues/106#issuecomment-242624950](url)
