### ISSUE TITLE
Duplicate module name: parse

### ISSUE THREAD

**Issue by etamity** [fbsamples/f8app#126]
## **I installed parse server and parse client sdk from npm, and got the naming collision error. Any idea?**

Failed to build DependencyGraph: @providesModule naming collision:
Duplicate module name: parse
Paths: /Users/etamity/Documents/etamity/dev/IOS/react/ultimateApp/node_modules/parse/package.json collides with /Users/etamity/Documents/etamity/dev/IOS/react/ultimateApp/node_modules/parse-server/node_modules/parse/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
Duplicate module name: parse
Paths: /Users/etamity/Documents/etamity/dev/IOS/react/ultimateApp/node_modules/parse/package.json collides with /Users/etamity/Documents/etamity/dev/IOS/react/ultimateApp/node_modules/parse-server/node_modules/parse/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
at HasteMap._updateHasteMap (/Users/etamity/Documents/etamity/dev/IOS/react/ultimateApp/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:155:13)
at p.getName.then.name (/Users/etamity/Documents/etamity/dev/IOS/react/ultimateApp/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:130:31)
at process._tickCallback (internal/process/next_tick.js:103:7)
~

**Comment by etamity** [comment]
{
  "name": "ultimateApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "babel-node ./server/server.js",
    "import-data": "babel-node ./scripts/import-data-from-parse.js",
    "update-schema": "babel-node ./server/schema/updateSchema.js",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "art": "~0.10.1",
    "babel-cli": "~6.16.0",
    "babel-preset-react-native": "^1.9.0",
    "babel-relay-plugin": "~0.9.1",
    "crc32": "~0.2.2",
    "express": "~4.14.0",
    "express-graphql": "~0.5.3",
    "graphql-relay": "~0.4.2",
    "moment": "~2.15.1",
    "parse": "^1.9.2",
    "parse-dashboard": "~1.0.8",
    "parse-server": "~2.2.22",
    "react": "15.3.2",
    "react-native": "0.34.1",
    "react-native-code-push": "~1.14.6-beta",
    "react-native-elements": "^0.6.0",
    "react-native-fbsdk": "^0.3.0",
    "react-native-linear-gradient": "~1.5.0",
    "react-native-push-notification": "github:frantic/react-native-push-notification#7142da7",
    "react-native-send-intent": "~1.0.7",
    "react-native-share": "github:frantic/react-native-share#674df947b3",
    "react-native-vector-icons": "^2.1.0",
    "react-redux": "~4.4.5",
    "react-relay": "~0.9.1",
    "react-timer-mixin": "~0.13.3",
    "redux": "~3.6.0",
    "redux-logger": "~2.6.1",
    "redux-persist": "~4.0.0-alpha5",
    "redux-thunk": "~2.1.0",
    "reselect": "~2.5.1"
  },
  "devDependencies": {
    "babel-eslint": "~7.0.0",
    "babel-jest": "~15.0.0",
    "babel-polyfill": "~6.16.0",
    "eslint": "~3.6.1",
    "eslint-plugin-react": "~6.3.0",
    "jest-cli": "~15.1.1"
  },
  "jest": {
    "haste": {
      "defaultPlatform": "ios",
      "platforms": [
        "ios",
        "android"
      ],
      "providesModuleNodeModules": [
        "react-native"
      ]
    }
  },
  "engines": {
    "node": ">=5.0",
    "npm": ">=3.0"
  }
}



this is the package.json from f8app

**Comment by Mausic** [comment]
I have the same problem.
How I encountered it:
1. Cloned repo
2. On '$ npm install' process hanged for a long time -> manually canceled.
3. Deleted  'npm-shrinkwrap.json'
4. ran '$ npm install' once again -> success
5. Steps 3-5 from 'read.me' -> success
6. '$ react-native run-ios' -> the same error as described above

System: 
- Mac OS X El Captain
- node -v 6.7.0
- npm -v 3.10.7

**Comment by etamity** [comment]
i found fixed it by removed "parse": "1.9.1" from package.json in the root.
Change "parse": "1.9.1" to "parse": "1.9.2" in node_modules/parse-server/package.json 

and then remove all node_modules then npm install again.

**Comment by ZainaliSyed** [comment]
Change "parse": "1.9.1" to "parse": "1.9.2" in node_modules/parse-server/package.json
works for me as well and  **Don't use YARN INSTALL  , Install Dependencies through  NPM INSTALL**
