### ISSUE TITLE
Red Screen - with error " Please Provide a Query String" 

### ISSUE THREAD

**Issue by gondar00** [fbsamples/f8app#128]
- I am running my parse server.
`npm start`
- I am running react-native start
`react-native start`

But still seeing the below screenshot. 
Can anyone help me? 

![screenshot from 2016-10-09 10 04 43](https://cloud.githubusercontent.com/assets/12490590/19217951/291bad80-8e08-11e6-92a6-242c6a0ae9c2.png)

**Comment by wayne-kim** [comment]
did you run mongodb?
