### ISSUE TITLE
 Build failed with an exception

### ISSUE THREAD

**Issue by ponickkhan** [fbsamples/f8app#131]
when i run: react-native run-android 
the build process fails with this error .any solution to this?

:app:processDebugManifest
G:\wamp\www\f8app\android\app\src\main\AndroidManifest.xml:58:11-70 Error:
        Attribute activity#com.facebook.FacebookActivity@theme value=(@android:style/Theme.Translucent.NoTitleBar) from AndroidManifest.xml:58:11-70
        is also present at [com.facebook.android:facebook-android-sdk:4.17.0] AndroidManifest.xml:32:13-63 value=(@style/com_facebook_activity_theme)
        Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:56:7-59:46 to override
:app:processDebugManifest FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:processDebugManifest'.
  
  > Manifest merger failed : Attribute activity#com.facebook.FacebookActivity@theme value=(@android:style/Theme.Translucent.NoTitleBar) from AndroidManifest.xml:58:11-70
  >     is also present at [com.facebook.android:facebook-android-sdk:4.17.0] AndroidManifest.xml:32:13-63 value=(@style/com_facebook_activity_theme)
  >     Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:56:7-59:46 to override
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 33.075 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by ponickkhan** [comment]
after adding   "tools:replace="@android:theme" in activity  its solves the problem 

file \f8app\android\app\src\main\AndroidManifest.xml in line 57

**Comment by ponickkhan** [comment]
with this solutionthe app get crashed if i try to skip the facebook login

**Comment by anmolakhilesh** [comment]
Having the same problem in Ubuntu 16.04

**Comment by vidcina** [comment]
I got the same problem

**Comment by pprinz** [comment]
Is there a solution for this problem? It crashes every time i want to start the app in the emulator...
