### ISSUE TITLE
alert error object object when try to connect with facebook and app crash when try to skip

### ISSUE THREAD

**Issue by ponickkhan** [fbsamples/f8app#132]
Any solution to this ? 

[https://www.youtube.com/watch?v=pR0k0jKrk-8&feature=youtu.be](https://www.youtube.com/watch?v=pR0k0jKrk-8&feature=youtu.be)

**Comment by ponickkhan** [comment]
previously i added tools:replace="android:theme" in the android manifest in activity before android:theme="@android:style/Theme.Translucent.NoTitleBar"

would it be the reason ? then what will be the fix ?

**Comment by ps-feng** [comment]
Same problem. Did you manage to find a fix?

**Comment by ps-feng** [comment]
Apparently it's some issue with the push notifications. I commented out the push notification references from the app's main page and could manage to get into the app.

**Comment by viveksnh** [comment]
Could you please give some detail on how you solved the issue? 
I am trying to learn react native and I am getting the same error "Alert [Object][Object]" when trying to log in.

**Comment by ps-feng** [comment]
Open `F8App.js` and comment out the following lines:
`this.props.dispatch(loadNotifications());` (x2)
and
`<PushNotificationsController />`
