### ISSUE TITLE
Android After SKIPPED_LOGIN Action Error hasUnreadNotifications

### ISSUE THREAD

**Issue by serkandyck** [fbsamples/f8app#133]
Facebook sdk 4.17.0 Have already setting notitle bar theme and get error Main Manifest Facebook activity theme for if u are delete app theme line screen appread but if u get skip login Get this error

Warning: Failed Context Types: Invalid child context `hasUnreadNotifications` of type `boolean` supplied to `F8TabsView`, expected `number`. Check the render method of `Connect(F8TabsView)`.

F8TabViews.js

getChildContext() {
    return {
      openDrawer: this.openDrawer,
      hasUnreadNotifications: this.props.notificationsBadge > 0,
    };
  }

And Some LogCat Error 

E/AndroidRuntime(  515): FATAL EXCEPTION: IntentService[RNPushNotification]
E/AndroidRuntime(  515): Process: com.facebook.f8, PID: 515
E/AndroidRuntime(  515): java.lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to class 'com.google.android.gms.iid.zzd' (declaration of 'com.google.android.gms.iid.zzd' appears in /data/app/com.facebook.f8-1/base.apk)
E/AndroidRuntime(  515):        at com.google.android.gms.iid.zzd.zzdL(Unknown Source)
E/AndroidRuntime(  515):        at com.google.android.gms.iid.zzd.<init>(Unknown Source)
E/AndroidRuntime(  515):        at com.google.android.gms.iid.zzd.<init>(Unknown Source)
E/AndroidRuntime(  515):        at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
E/AndroidRuntime(  515):        at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
E/AndroidRuntime(  515):        at com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService.onHandleIntent(RNPushNotificationRegistrationService.java:20)
E/AndroidRuntime(  515):        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/AndroidRuntime(  515):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(  515):        at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(  515):        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by prijindal** [comment]
I am facing the same issue
any solutions?

**Comment by lucamtudor** [comment]
`hasUnreadNotifications` is supposed to be a number. `hasUnreadNotifications: this.props.notificationsBadge > 0` will evaluate the property to a boolean. I just deleted `> 0`...
 See [declaration type](https://github.com/fbsamples/f8app/blob/master/js/tabs/F8TabsView.android.js#L226).

I don't want to be a hater, but this is a good reason why JavaScript/[enter dynamic language] is shit.

**Comment by mjet08** [comment]
I have tried to remove `>0` from `hasUnreadNotifications`, but still it is not working

**Comment by rendongsc** [comment]
how to solve this issue?

**Comment by mjet08** [comment]
I finally solved this issue by doing the following changes 

comment out those lines in F8App.js

 render: function() {
    // if (!this.props.isLoggedIn) {
    //   return <LoginScreen />;
    // }
    return (
      <View style={styles.container}>
        <StatusBar
          translucent={true}
          backgroundColor="rgba(0, 0, 0, 0.2)"
          barStyle="light-content"
         />
        <F8Navigator />
      </View>
    );
  },

});

please make sure that you remove <PushNotificationController> in that code


`do the following changes in setup.js`

 render() {
      // if (this.state.isLoading) {
      //  return null;
      // }
      return (
        <Provider store={this.state.store}>
          <F8App />
        </Provider>
      );

so this will load directly your main screen showing schedules and navigation drawer
