### ISSUE TITLE
App shows error " could not connect to development server"

### ISSUE THREAD

**Issue by mjet08** [fbsamples/f8app#136]
I have followed all the steps mentioned in the guidelines on my windows 8 machine, and after `react-native run-android` command apk is also built successfully and then the app starts connecting to js server , but then error comes "could not connect to development server". 
![issue](https://cloud.githubusercontent.com/assets/17106620/20095594/15768e68-a5cc-11e6-8efb-4229c7ef4b20.png)

**Comment by lucamtudor** [comment]
I just had and fixed the same problem.
Make sure you have:
- mongodb installed and started: mongod --dbpath path-to-where-you-want-mongo-to-save-shit
- parse and graphql started: npm start. import data, but not relevant
- adb sees your device
- run the reverse commands: 
      adb reverse tcp:8081 tcp:8081
      adb reverse tcp:8080 tcp:8080
- when you run `react-native run-android` make sure a new terminal is launched with the package manager. sometimes you just have to run `react-native run-android` a couple times...

**Comment by mjet08** [comment]
ok,I have followed all the steps as you have said,but the error remains the same.

**Comment by Kongdy** [comment]
I also picked this problem.And it does't work after I followed all the steps.

**Comment by holumyn** [comment]
Could anyone please point me to the right direction because i just encountered this challenge?
