### ISSUE TITLE
** BUILD FAILED ** Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by byteware** [fbsamples/f8app#137]
Hi guys,

I am running latest xcode package and have a local clone of f8app. Did follow the README doco. 

I am getting the following error. The CFBundleIdentifier is present in the Info file. 

Could you please help.

Thanks

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/name/src/projects/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTScrollView.o /Users/name/src/projects/f8app/node_modules/react-native/React/Views/RCTScrollView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/F8v2.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/name/src/projects/f8app/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/F8v2.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:470:13)
    at Object.execFileSync (child_process.js:490:13)
    at _runIOS (/Users/name/src/projects/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:82:32)
    at /Users/name/src/projects/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5
    at tryCallTwo (/Users/name/src/projects/f8app/node_modules/react-native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/name/src/projects/f8app/node_modules/react-native/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/name/src/projects/f8app/node_modules/react-native/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/name/src/projects/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
    at Object.run (/Users/name/src/projects/f8app/node_modules/react-native/local-cli/cliEntry.js:96:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:116:7)

**Comment by rwilliamselab** [comment]
I'm get exactly the same problem

**Comment by rgamba** [comment]
Same here

**Comment by alxmrtnz** [comment]
Has anyone got this working? I'm also having the same issue.

**Comment by Zuela** [comment]
Same here. Anyone able to get past this?

**Comment by uglybachelor** [comment]
Same here

**Comment by arniu** [comment]
Same here

**Comment by Deepsilence-tcc** [comment]
same with me. Anyone work it? please past.

**Comment by lizilong007** [comment]
same with me .I'm try react-native upgrade,then execute react-native run-ios, build success.I made it! but show me a new problem. native module cannot be null..........

**Comment by lizilong007** [comment]
I made it!
My environment:

- xcode 8.1

- node 5.7

- npm 3.6

first run. 1.npm install   2. cd ios &&  pod install --no-repo-update 
Then.open the project in xcode 1.run the project(command+R) , Will you can see some errors.if those errors look like the pictrue
![qq20161130-0](https://cloud.githubusercontent.com/assets/15603767/20756536/ff31d4e4-b74d-11e6-8818-79eaa33a635d.png)
Like I do and then run it.

**Comment by wachirakorn** [comment]
Same with me. Waiting.

**Comment by Aloundev** [comment]
Use Online Mongodb instead of the localhost (solved)

**Comment by chengxianghe** [comment]
Sorry, my English is poor, the problem is in the presence of ios10, because the API name refreshControl conflict with the system, it should be the better "refreshControl" to other name, such as "myRefreshControl".And some of the above code also needs corresponding changes.

https://github.com/chengxianghe/watch-gif/blob/master/temp/RCTScrollView(modified).m

**Comment by YarGnawh** [comment]
I got the same error too and fixed it by adding this line:

![image](https://cloud.githubusercontent.com/assets/130418/22573111/65148384-e975-11e6-9dbe-8a75acb45f47.png)

Because ```- (void)setRefreshControl:(RCTRefreshControl *)refreshControl``` was defined, it compiler doesn't automatically syntheize ```_refreshControl```

**Comment by monaLeti** [comment]
@lizilong007 It works for me! Thank you

**Comment by hatoriz** [comment]
@YarGnawh it works ! Thank you very much

**Comment by justinhaaheim** [comment]
@YarGnawh have you created a pull request for this? If not, would you?

**Comment by code-smith** [comment]
@YarGnawh make a PR for this please

**Comment by eGirlAsm** [comment]
@YarGnawh good!

**Comment by sunsmeil** [comment]
pod install The target `F82017-tvOSTests` is declared twice
