### ISSUE TITLE
App launches with Home Screen. On skipping login by clicking close 'X', App Crashes.  

### ISSUE THREAD

**Issue by abhijithcs** [fbsamples/f8app#142]
"Unable to connect to the Parse API" is the error appeared on Debugger. 
![screen shot 2016-12-07 at 1 03 40 pm](https://cloud.githubusercontent.com/assets/4880883/20958832/ada9d6dc-bc7d-11e6-8078-9e4b6a86365a.png)

**Comment by ichagas** [comment]
You need to setup Parse Server correctly. There is nothing special, just:

1) Install the MongoDB locally, if you haven't yet. Or use a online instance
2) Run Parse Server with `npm start` => before run the App

Just follow the instructions in the main page.

**Comment by Grundmanis** [comment]
Same for me.. MongoDb installed, parse server is running, data imported..

**Comment by ichagas** [comment]
Check the environment variable mongo_uri

Go to terminal and type `env` 

In the list make sure there is no reference to any mongoDb uri. This is going to force the Parse Serve to use local MongoDB

Also check the Web Browser if you get access to `http://localhost:8080/dashboard`

**Comment by abhijithcs** [comment]
Yeah, that was an issue with `npm start`. Got sorted out :)

**Comment by anasjafry** [comment]
I faced the same issue, try running the commands in the same order as mentioned in readme. Worked for me.
