### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by arjunpola** [fbsamples/f8app#144]
Encountered the following error when running `react-native run-android`. And solved it by adding `tools:replace="android:theme` to the AndroidManifest.xml in `<activity android:name="com.facebook.FacebookActivity".........`

Please make the correction.

<img width="1230" alt="screen shot 2016-12-18 at 1 02 34 am" src="https://cloud.githubusercontent.com/assets/4324936/21292541/0abdcb4c-c4be-11e6-9e07-923feb632948.png">

**Comment by hqt** [comment]
In **Android Manifest** file, you change **FacebookActivity** to this:

```
      <activity android:name="com.facebook.FacebookActivity"
          android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
          android:theme="@android:style/Theme.Translucent.NoTitleBar"
          tools:replace="android:theme"
          android:label="@string/app_name" />

```

**Comment by ralberts** [comment]
Thanks @hqt That helped me get past the build error - though my f8 is crashing on my now at the login screen.

**Comment by hqt** [comment]
I think this source code doesn't maintain anymore. Author doesn't reply to any issues now.
