### ISSUE TITLE
Cannot build on Windows 7

### ISSUE THREAD

**Issue by hugows** [fbsamples/f8app#147]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "C:\\Users\\hugo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "insta
ll"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","a
rch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

**Comment by Steviey** [comment]
+1 
also "lsof -iTCP:27017 -sTCP:LISTEN" is not recognized as internal or external command.

**Comment by boliveira** [comment]
To fix this, remove fsevents entry from npm-shrinkwrap.json and do a npm install again.
fsevents is a module that requires macOS...
lsof is a UNIX command to check if a port is open. On Windows you can use TcpView to ensure the port 27017 is listening by mongod.exe
