### ISSUE TITLE
Non GraphQL version

### ISSUE THREAD

**Issue by hffmnn** [fbsamples/f8app#148]
Hi there,

in your documentation at http://makeitopen.com/ you say, that there was a non-GraphQL version, but I can not find it in the commit history. Personally I think it would be SUPER useful to have the non-GraphQL available, because not everyone has the chance to switch over from a classic REST API  to GraphQL, so having this by hand and see how you implemented that together with Redux would be very useful.

What do you think? Would this be somehow possible?

**Comment by Steviey** [comment]
+1

**Comment by Lipfroy** [comment]
+1

**Comment by grantolive** [comment]
ok
contact me here:: gigi598955.@gmail.com .

**Comment by vko-online** [comment]
Just remove `server/schema/`, remove references from `server.js`, remove references from `js/common/ListContainer, js/tabs/info/F8InfoView`. Remove deps from package.json That's it
