### ISSUE TITLE
import data error?

### ISSUE THREAD

**Issue by stefan321** [fbsamples/f8app#149]
npm run import-data

> F8v2@0.0.1 import-data /Users/stefan321/Documents/F8 App 2016/f8app
> babel-node ./scripts/import-data-from-parse.js

Loading Speakers
SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/stefan321/Documents/F8 App 2016/f8app/node_modules/node-fetch/lib/body.js:43:15
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

how can i fix it?
run mongodb 
run npm start is ok

**Comment by kaka09** [comment]
Because Parse server is shutdown.

**Comment by lixiaoguang-xiaoniu** [comment]
I also met this issue, is this issue related with react native version?

**Comment by Eluss** [comment]
@kaka09 is right. If you log text from the response, you will see:
`Parse.com has shutdown - https://parseplatform.github.io/`
That's where `Unexpected token P` comes from

**Comment by j2kun** [comment]
So... Can you put a copy of the data in the repo and load from static json?

**Comment by lichengqi** [comment]
Is there any announcements about when to publish an alternate address?

**Comment by iossocket** [comment]
Or provide a static json file for testing.

**Comment by alejoar** [comment]
Can someone provide a json file for testing, please?

**Comment by sillyfish** [comment]
up up,how to test this app without parse? eager to  know~

**Comment by rozele** [comment]
Hey guys, fortunately, I have an old copy of the data from when I was developing the F8App on react-native-windows.  If you haven't checked out https://github.com/ReactWindows/react-native-windows, you should!  You should also check out our fork of the F8App, https://github.com/ReactWindows/f8app to see how easy it can be to add UWP support to your application.

Okay, back to the issue at hand.  Unfortunately, there's a bug in mongodump.exe that is not allowing me to produce a proper export of this data.  However, I was able to zip up my current MongoDB data folder, which I suspect may help you guys out.

Please note, this database folder was produced using MongoDB 3.2.5 on Windows, so presumably you may only be able to consume this data on a similar setup.

You can download the file from: https://github.com/ReactWindows/f8app/blob/data/mongodb/db.zip

**Comment by sillyfish** [comment]
@rozele it works well, tks~

**Comment by alejoar** [comment]
@rozele Thank you.

Sorry for the off topic; my company is interested in developing an app for windows phone. What's the current status of react-native for windows? Do you guys have an official website with api docs and stuff or is it just the github repo? Is it possible to develop and run on virtual devices from linux?

**Comment by rozele** [comment]
@alejoar The current status of react-native-windows is that we're publishing releases to align with monthly react-native releases. The last major release was 0.39, but we have release candidates out for 0.40, 0.41, and 0.42.  You can use react-native-windows to build apps for Windows 10 Desktop, Mobile, Xbox, and HoloLens. There has also been some work to bring react-native-windows to earlier versions of Windows desktop (7 and 8.1) using WPF.

There is no official website for react-native-windows, just the GitHub repo.  There's a README and a few tutorials in the ./docs/ folder.  Unfortunately there are no Windows emulators that run on Linux, but you can dual boot or use Virtual Box or some other VM.

**Comment by alejoar** [comment]
@rozele <https://github.com/rozele> thank you. I'll be exploring
react-native-windows in the next few days and hopefully use it for our next
project.

**Comment by brucebnu** [comment]
how to “npm run import-data” on mac OX，Any offline data?

**Comment by CarGuo** [comment]
+1

**Comment by yuguangmao** [comment]
+1

**Comment by onezens** [comment]
how to fix it?

**Comment by bullwrinkle** [comment]
+1

**Comment by dezoy** [comment]
work on mongodb 3.4, thank you @rozele
