### ISSUE TITLE
Sharing functionality crashes (iOS and Android)

### ISSUE THREAD

**Issue by shaialon** [fbsamples/f8app#15]
undefined is not an object (evaluating 'sessionURLTemplate.replace')
<img width="501" alt="screen shot 2016-04-18 at 2 37 04 pm" src="https://cloud.githubusercontent.com/assets/3126207/14602877/0b535e4c-0573-11e6-8cd9-ea54cd68bdfe.png">

See attached gif:
![ezgif-2850324779](https://cloud.githubusercontent.com/assets/3126207/14602849/d5687be6-0572-11e6-8a0c-02ec0d9373f8.gif)

**Comment by frantic** [comment]
Great catch! That's because the app loads the sharing URL template from Parse Config (and I didn't include setting this up in README).
