### ISSUE TITLE
SyntaxError when running `npm run import-data`

### ISSUE THREAD

**Issue by tin-tnguyen** [fbsamples/f8app#150]
> F8v2@0.0.1 import-data /Users/tin/Sites/f8app
> babel-node ./scripts/import-data-from-parse.js

Loading Speakers
SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/tin/Sites/f8app/node_modules/node-fetch/lib/body.js:43:15
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

**Comment by iossocket** [comment]
How did you solve this problem? Thanks

**Comment by tin-tnguyen** [comment]
@iamscott still haven't solved yet.
The ticket was closed because I found it duplicated then. However I am still looking for a solution either new update in master branch.
