### ISSUE TITLE
parse.com is shutdown, cannot run the f8 app

### ISSUE THREAD

**Issue by saycchai** [fbsamples/f8app#151]
parse.com is shutdown, what should we do in order to import the data and run the app?

![f8](https://cloud.githubusercontent.com/assets/7637215/22765890/948dca84-eead-11e6-9541-f7dc67e8e17c.png)

**Comment by xcuYao** [comment]
same as [149](https://github.com/fbsamples/f8app/issues/149) 
when run 'npm run import-data'
the https://api.parse.com/1/classes/***
has shutdown.

**Comment by saycchai** [comment]
I know that. My question is "parse.com is shutdown, what should we do in order to import the data and run the app?"

**Comment by chenzhen0592** [comment]
same issue:
https://github.com/fbsamples/f8app/issues/149

**Comment by brucebnu** [comment]
+1
