### ISSUE TITLE
api.parse.com Shutdown How to import data? 

### ISSUE THREAD

**Issue by brucebnu** [fbsamples/f8app#154]
Hi, genius

api.parse.com Shutdown，
⇒  npm run import-data

> F8v2@0.0.1 import-data /Users/bruceniu/Documents/GitHub/f8app
> babel-node ./scripts/import-data-from-parse.js

Loading Speakers
SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/bruceniu/Documents/GitHub/f8app/node_modules/node-fetch/lib/body.js:43:15
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

code
async function importClass(className) {
  console.log('Loading', className);
  const response = await fetch(`https://api.parse.com/1/classes/${className}`, {
    method: 'get',
    headers: {
      'X-Parse-Application-Id': 'R0yDMIKCUyEke2UiadcTBBGd1L5hMBTGJSdBNL3W',
      'X-Parse-JavaScript-Key': 'BJ5V0APFMlvmCBPDXl9Mgh3q3dFrs18XkQz6A2bO',
      'Content-Type': 'application/json'
    },
  });
  const {results} = await response.json();
  const ClassType = Parse.Object.extend(className);
  console.log('Cleaning old', className, 'data');
  await new Parse.Query(ClassType)
    .each(record => record.destroy());
  console.log('Converting', className);
  return Promise.all(results.map(attrs => importObject(ClassType, attrs)));
}

Thank you very much！

**Comment by liangxiaowei** [comment]
I solve this problem by these steps:
1. download https://github.com/ReactWindows/f8app/blob/data/mongodb/db.zip
2. install mongoDB by:
    ###### brew install mongodb
3. start mongoDB server by: 
    ###### mongod   --dbpath  YOURDATAPATH  //the path you just downLoaded
4. start mongoDB client by:
    ###### mongo

Here is an article(in Chinese) you can refer to: http://www.jianshu.com/p/f7cb35436f9a

**Comment by hari-mohan-choudhary** [comment]
@liangxiaowei how install db.zip in linux

**Comment by hari-mohan-choudhary** [comment]
thanks @liangxiaowei
