### ISSUE TITLE
Parse.com has been shutdown

### ISSUE THREAD

**Issue by drinkingcode** [fbsamples/f8app#157]
when I type "npm run import-data" in terminal, it outputs as following:

SyntaxError: Unexpected token P in JSON at position 0
    at Object.parse (native)
    at /Users/hello/f8app/node_modules/node-fetch/lib/body.js:43:15
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

Then, I find the import-data-from-parse.js :

async function importClass(className) {
  console.log('Loading', className);
  //the reason is here
 //parse.com shutdown
  const response = await fetch(`https://api.parse.com/1/classes/${className}`, {
    method: 'get',
    headers: {
      'X-Parse-Application-Id': 'R0yDMIKCUyEke2UiadcTBBGd1L5hMBTGJSdBNL3W',
      'X-Parse-JavaScript-Key': 'BJ5V0APFMlvmCBPDXl9Mgh3q3dFrs18XkQz6A2bO',
      'Content-Type': 'application/json'
    },
  });
  const {results} = await response.json();
  const ClassType = Parse.Object.extend(className);
  console.log('Cleaning old', className, 'data');
  await new Parse.Query(ClassType)
    .each(record => record.destroy());
  console.log('Converting', className);
  return Promise.all(results.map(attrs => importObject(ClassType, attrs)));
}

So that's why running import-data results in the error.
 because parse.com website has been shutdown !
is there any solution to import data or how can I get the json file ? 
if you know that , please tell me .
thank you, guys !

**Comment by jagatfx** [comment]
Follow instructions at the following for downloading and importing the data into your local mongo without using import-data: https://github.com/fbsamples/f8app/issues/156#issuecomment-287044271

**Comment by WillSmithInChina** [comment]
@jagatfx thanks!
