### ISSUE TITLE
react-native run-android  error

### ISSUE THREAD

**Issue by tigerohuang** [fbsamples/f8app#16]
I run react-native run-android and got the following error, please tell me how to solve it.

Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug...
> Configuring > 5/7 projects > Resolving dependencies ':react-native-push-notification:_debugCompile'

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-push-notification'.
   > Could not resolve all dependencies for configuration ':react-native-push-notification:_debugCompile'.
      > Could not find com.google.android.gms:play-services-gcm:8.3.0.
        Searched in the following locations:
            file:/Users/hqr/.m2/repository/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.pom
            file:/Users/hqr/.m2/repository/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.jar
            https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.pom
            https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.jar
            file:/Users/hqr/reactnative/demos/f8app/node_modules/node_modules/react-native/android/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.pom
            file:/Users/hqr/reactnative/demos/f8app/node_modules/node_modules/react-native/android/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.jar
            file:/usr/local/opt/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.pom
            file:/usr/local/opt/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.jar
        Required by:
            F8v2:react-native-push-notification:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 52.259 secs

**Comment by frantic** [comment]
This is the important line

> Could not find com.google.android.gms:play-services-gcm:8.3.0.

Likely that's because you haven't installed Android Play Services from Android SDK. Try running `android` from your terminal and making sure these are installed:

![image](https://cloud.githubusercontent.com/assets/192222/14617002/5ce027ca-0561-11e6-8f90-1be6de1d860b.png)
