### ISSUE TITLE
Help!!!pod install error

### ISSUE THREAD

**Issue by wyqwsg04** [fbsamples/f8app#162]
Analyzing dependencies
Fetching podspec for `CodePush` from `../node_modules/react-native-code-push`

[!] Invalid `CodePush.podspec` file: no implicit conversion of nil into String.

 #  from /Users/lsc/Desktop/React Native/f8app/node_modules/react-native-code-push/CodePush.podspec:3
 #  -------------------------------------------
 #  
 >  package = JSON.parse(File.read(File.join(__dir__, 'package.json')))
 #  
 #  -------------------------------------------

**Comment by cs0511** [comment]
same issue of me
