### ISSUE TITLE
Updated F8 source code WANTED!

### ISSUE THREAD

**Issue by binzailani3136** [fbsamples/f8app#164]
Hi
I've seen that F8 app is updated on Google Play but this repo is still old version app.
Do you have any plan to update this repo with new version?
Thanks

**Comment by Lenin7** [comment]
Any updates on this?

**Comment by binzailani3136** [comment]
No updates yet.

**Comment by Lenin7** [comment]
Last year the source code was released 1 moth before F8. Doesnt seem like they'll be releasing it this year

**Comment by tanpuer** [comment]
I have downloaded f8app from GooglePlay. It is great! Please update the source code

**Comment by Lenin7** [comment]
Doesnt seem like this post is getting any attention from facebook. Maybe we can @mention a few people who worked on the app last year?

**Comment by Tiendq** [comment]
Just found F8app from App Store is different from source code :(

**Comment by Dssdiego** [comment]
On Android is different too...

**Comment by gaving** [comment]
Chiming in to say it's a bit disappointing this repo isn't maintained, it's sort of become a big example of a fairly functional app.

**Comment by pmachowski** [comment]
@frantic any plans on open sourcing F8 2017 app?

**Comment by ask007java** [comment]
@frantic please respond.

**Comment by Lenin7** [comment]
@frantic ?

**Comment by frantic** [comment]
I'm​ sorry folks, there's nothing planned yet.

**Comment by frantic** [comment]
Check out https://github.com/fbsamples/f8app/pull/185
