### ISSUE TITLE
mongo run error

### ISSUE THREAD

**Issue by gzponline** [fbsamples/f8app#165]
system ：ubuntu
start mongo ： I use servise mongodb start 
and i do as readme.md 

 lsof -iTCP:27017 -sTCP:LISTEN
 
export DATABASE_URI=mongodb://example-mongo-hosting.com:1337/my-awesome-database

and npm start
but

Error generating response. { MongoError: failed to connect to server [example-mongo-hosting.com:1337] on first connect

how to do 

![](http://upload-images.jianshu.io/upload_images/1889471-35fff3ab9b5bbbdd.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by hichamelkaddioui** [comment]
You have to run `export DATABASE_URI=mongodb://example-mongo-hosting.com:1337/my-awesome-database` only if you wish to connect to a remote database. Ignore this step if you run mongodb locally.
