### ISSUE TITLE
load js with error:response error code 400

### ISSUE THREAD

**Issue by xsgkaka** [fbsamples/f8app#17]
i have buided success,i got the correct  result when i use my browser to vist `http://localhost:8080/graphql`.but when i run the F8 app on my android device, i got the red screen,the response error.like this:
`{
  "errors": [
    {
      "message": "Must provide query string."
    }
  ]
}`. how to solve this error? thanks in  advance.

**Comment by frantic** [comment]
Make sure your `adb reverse tcp:8080 tcp:8080` works. You could also try changing `serverURL` in `js/env.js` file to point to your computer's IP.

**Comment by xsgkaka** [comment]
i execute `adb reverse tcp:8080 tcp:8080` command ，and change the  `serverURL ` in the `js/env.js` file to point to my ip.but i still get the same error.

**Comment by xsgkaka** [comment]
yes， i got it. i fogot to run `react-native start ` comand. ^_^. Please close this issue. thanks

**Comment by TammyWorley** [comment]
Do not send any thing to me Someone stole my name and e mail. Anthony at
texasoutlaw10992276@gmail.com Did.
