### ISSUE TITLE
Err: :app:processDebugManifest FAILED

### ISSUE THREAD

**Issue by nisdis** [fbsamples/f8app#171]
Ran:
 $ react-native run-android

Here is the error: 

`* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute activity#com.facebook.FacebookActivity@theme value=(@android:style/Theme.Translucent.NoTitleBar) from AndroidManifest.xml:55:11-70
  	is also present at [com.facebook.android:facebook-android-sdk:4.22.0] AndroidManifest.xml:32:13-63 value=(@style/com_facebook_activity_theme)
  	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:53:7-56:46 to override

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
`

**Comment by shashankbarsin** [comment]
Remove android:theme="@android:style/Theme.Translucent.NoTitleBar" 
from 
f8app/android/app/src/main/AndroidManifest.xml

**Comment by nisdis** [comment]
Hi thanks,

It did fix it, but I did run into plenty of more errors. I guess the f8v2 app doesn't work out of the box as described
