### ISSUE TITLE
Manifest merge error

### ISSUE THREAD

**Issue by hariramsvnit** [fbsamples/f8app#172]
I am getting this error while building app for android:
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute activity#com.facebook.FacebookActivity@theme value=(@android:style/Theme.Translucent.NoTitleBar) from AndroidManifest.xml:55:11-70
  	is also present at [com.facebook.android:facebook-android-sdk:4.22.0] AndroidManifest.xml:32:13-63 value=(@style/com_facebook_activity_theme)
  	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:53:7-56:46 to override

**Comment by sjy** [comment]
I have met up with the same issue.
