### ISSUE TITLE
Will F8 app of 2017 be released?

### ISSUE THREAD

**Issue by xareelee** [fbsamples/f8app#174]
Is F8 app of 2017 also written in React Native?

Will it be released as an open-source project?

**Comment by jackqqxu** [comment]
mark

**Comment by janreyho** [comment]
+1

**Comment by florianmari** [comment]
Sorry but no, there's nothing planned for updating this source code > #164

**Comment by frantic** [comment]
F8 2017 is here https://github.com/fbsamples/f8app/pull/185
