### ISSUE TITLE
com.android.ide.common.process.ProcessException

### ISSUE THREAD

**Issue by nobuts-yep** [fbsamples/f8app#175]
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:Execution failed for task ':react-native-fbsdk:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/xxxxx/Library/Android/sdk/build-tools/25.0.0/aapt'' finished with non-zero exit value 1

**Comment by tlrk** [comment]
I have the same problem

**Comment by kisubs** [comment]
Same error message :(

**Comment by 867380699** [comment]
save error

**Comment by kisubs** [comment]
https://stackoverflow.com/questions/44190829/facebook-sdk-android-error-building 
First answer helped me solve this error.

**Comment by Arshiamidos** [comment]
app/build.gradle
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"

    defaultConfig {

**Comment by santhosh77h** [comment]
both  `compileSdkVersion` and `buildToolsVersion` should be same taken from [here](https://blog.csdn.net/shakdy/article/details/54861919)
