### ISSUE TITLE
message: request api.parse.com failed,reason:certificate has expired

### ISSUE THREAD

**Issue by sj-m** [fbsamples/f8app#178]
Loading Speakers
{ FetchError: request to https://api.parse.com/1/classes/Speakers failed, reason: certificate has expired
    at ClientRequest.<anonymous> (/Users/jiamin/Downloads/f8app-master/node_modules/node-fetch/index.js:127:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  name: 'FetchError',
  message: 'request to https://api.parse.com/1/classes/Speakers failed, reason: certificate has expired',
  type: 'system',
  errno: 'CERT_HAS_EXPIRED',
  code: 'CERT_HAS_EXPIRED' }

**Comment by AlexPuleio** [comment]
Same issue.

**Comment by Yu-w** [comment]
Same issue.

**Comment by RoyLR** [comment]
Same issue.

**Comment by mengtingluo** [comment]
Same issue.Hope it can be solved quickly.

**Comment by qiushi2012** [comment]
Same issue.Hope it can be solved quickly.

**Comment by xiaomaer** [comment]
Same issue.How to solve?

**Comment by fazlurr** [comment]
Anyone has an offline version of this database?

**Comment by WwoeSsi** [comment]
Same issue.

**Comment by Sheldon-XieRu** [comment]
+1

**Comment by cgf120** [comment]
Same issue

**Comment by michalko** [comment]
Same issue.Hope it can be solved quickly.

**Comment by wufei608** [comment]
Same issue.

**Comment by HizkiaLemuel** [comment]
Same issue

**Comment by maciejbak85** [comment]
same :(

**Comment by wsuper** [comment]
同样的问题啊，发一个数据库离线版本

**Comment by qgqceo** [comment]
+1

**Comment by asaldivar** [comment]
+1

**Comment by carlosbdw** [comment]
Yes, I met same issue yesterday , after spending a night I could run the iOS app now . please have a look this [https://github.com/fbsamples/f8app/issues/156](url)

**Comment by elbertcastaneda** [comment]
+1

**Comment by byk04712** [comment]
+1

**Comment by byk04712** [comment]
I resolved this problem. I just edited `import-data-from-parse.js`.   see below

```
async function importClass(className) {
  console.log('Loading', className);
  //const response = await fetch(`https://api.parse.com/1/classes/${className}`, {
  const response = await fetch(`http://localhost:8080/parse/classes/${className}`, {
    method: 'get',
    // headers: {
      // 'X-Parse-Application-Id': 'R0yDMIKCUyEke2UiadcTBBGd1L5hMBTGJSdBNL3W',
      // 'X-Parse-JavaScript-Key': 'BJ5V0APFMlvmCBPDXl9Mgh3q3dFrs18XkQz6A2bO',
      // 'Content-Type': 'application/json'
    // },
    headers: {
      'X-Parse-Application-Id': 'oss-f8-app-2016',
      'Content-Type': 'application/json'
    }
  });
```

**Comment by AnswerZhao** [comment]
same issue

**Comment by aawaheed** [comment]
Please see [https://github.com/fbsamples/f8app/issues/154](Download DB).

I solve this problem by these steps:
    download https://github.com/ReactWindows/f8app/blob/data/mongodb/db.zip
    start mongoDB server by:
`    mongod --dbpath YOURDATAPATH //the path you just downLoaded`
    start mongoDB client by:
`    mongo`

**Comment by stepharr** [comment]
I followed [#154](https://github.com/fbsamples/f8app/issues/154), and edited `import-data-from-parse.js` as well but the import hangs.

**Comment by fraserjamieson** [comment]
is no one discussing what the error revolves around? Newbie over here but i thought that was common place on most developer Q&A websites?
