### ISSUE TITLE
js/playground.js

### ISSUE THREAD

**Issue by yejodido** [fbsamples/f8app#18]
Any need for this now that the app has launched and the conference is over?

**Comment by frantic** [comment]
It's still useful to experiment with rendering the `<Playground />` component instead of `<F8App />` component from `setup.js`. I wanted to extract `Playground` into its own library but didn't have time to do it yet.

**Comment by TammyWorley** [comment]
Do not send any thing to me. Someone stole my name and e mail. Anthony at
texasoutlaw10992276@gmail.com... Did
