### ISSUE TITLE
use of var vs let/const

### ISSUE THREAD

**Issue by bl4ckm0r3** [fbsamples/f8app#186]
There are a lot of `var` in the code, sometimes mixed with let and const in the same file.
Is there a reason why?

**Comment by frantic** [comment]
No particular reason, likely was missed during various code upgrades. Feel free to send a pull request :)

**Comment by frantic** [comment]
If you want to make it even better—add a lint rule + autofix (e.g. https://eslint.org/docs/rules/no-var)

**Comment by bl4ckm0r3** [comment]
@frantic https://github.com/fbsamples/f8app/pull/188

**Comment by oclbdk** [comment]
@bl4ckm0r3, thanks for raising the issue and fixing it!
