### ISSUE TITLE
hello! Long Time no see

### ISSUE THREAD

**Issue by phpsmarter** [fbsamples/f8app#187]
Hi! very excited.Last year I learned a lot of RN skills from F8app 2016.Now have a new version.
I think maybe  support for expo and graphcool are good idea.

**Comment by oclbdk** [comment]
For sure, we're excited too! I'm glad it's helpful. Expo and GraphCool are great technologies, and we'd love to see PR's for them. As of now, adding support for them ourselves isn't a priority
