### ISSUE TITLE
There's an error when I run the react-native run-android command.

### ISSUE THREAD

**Issue by GarveyZuo** [fbsamples/f8app#189]
![image](https://user-images.githubusercontent.com/22234081/33895412-6bd2df46-df9b-11e7-9e99-bacb7881c80c.png)
I'm sure I have installed the Android API27 with Android Studio SDK Manager just like that:
![image](https://user-images.githubusercontent.com/22234081/33895573-c2744f38-df9b-11e7-9e1a-628dbce0a15c.png)
but it can't  work。

**Comment by ck227** [comment]
https://stackoverflow.com/questions/47671206/getting-error-when-run-react-native-run-android

**Comment by GarveyZuo** [comment]
thank you ! It works

**Comment by wmilewski** [comment]
In my case this only built for `facebook-android-sdk:4.22.0` and below.

**Comment by caabernathy** [comment]
Closing this out.
