### ISSUE TITLE
Duplicate declaration "value" error

### ISSUE THREAD

**Issue by Sunil-tc** [fbsamples/f8app#193]
I'm getting the below error while building app,

error: bundling: TypeError: f8app/js/filter/FilterScreen.ios.js: Duplicate declaration "value"

toggleTopic(topic: string, value: boolean) {
    const selectedTopics = { ...this.state.selectedTopics };
    const value = !selectedTopics[topic];
    if (value) {
         selectedTopics[topic] = true;
    } else {

**Comment by armenbadalyan** [comment]
Fixed by removing the second parameter of toggleTopic method.

```
toggleTopic(topic: string) {
    const selectedTopics = { ...this.state.selectedTopics };
    const value = !selectedTopics[topic];
    if (value) {
      selectedTopics[topic] = true;
    } else {
      delete selectedTopics[topic];
    }
    this.setState({ selectedTopics });
  }
```

**Comment by gengjiawen** [comment]
This has been fixed via https://github.com/fbsamples/f8app/pull/190.
