### ISSUE TITLE
No Native Module using react native

### ISSUE THREAD

**Issue by yaidelferrales** [fbsamples/f8app#194]
After following all the steps for installing react-native-fbsdk (https://github.com/facebook/react-native-fbsdk) I'm not able to use the sdk. I'm getting the error "undefined is not an object (evaluating 'LoginManager.logInWithReadPermissions')" and after some digging I found that require('react-native').NativeModules, returns an empty object. The issue appears in both android and ios.

node: 8.9.3
react-native: 0.50.3

As a side note I'm using StackNavigator

**Comment by caabernathy** [comment]
Is this issue related to running the f8 app? It's not clear from your description if that's the case or if this issue belongs to the react-native-fbsdk project. Let us know steps to reproduce for how to get to this after installing the f8 app.

**Comment by caabernathy** [comment]
We'll close this issue out within the next week if we don't get more details.

**Comment by ayushmankd** [comment]
Have you followed the instructions for installing react-native-fbsdk correctly?

Check the react-native version
