### ISSUE TITLE
F8 2018

### ISSUE THREAD

**Issue by letientai299** [fbsamples/f8app#202]
Will this repo be updated for the [F8 2018 event](https://developers.facebook.com/blog/post/2017/10/24/join-us-f8-2018/)?

**Comment by onpaws** [comment]
F8 2018 is over! Hope everyone that attended had a great time.

I'm curious about f8app. Last year users had to wait until [December 4](https://github.com/fbsamples/f8app/commit/522265d6b7778a8d6c94ed11d78532b943e3f52f).
What can you share? 

Thank you for your effort in helping share this lovely repo!

**Comment by onpaws** [comment]
Hi @frantic,
It's July now, I see the latest tag is still from 2017. Would appreciate any news that you could share? :)
Thanks

![image](https://user-images.githubusercontent.com/182515/43049241-a472c19c-8df4-11e8-9103-8eaea6516d70.png)
