### ISSUE TITLE
Parse issues in dev, f8 official ios/android app as well

### ISSUE THREAD

**Issue by sumitsavla** [fbsamples/f8app#211]
Check attached screenshots from official apps.
I am facing same "unable to connect parse API" issue in my local android app in emulator. 
let me know how to fix it.. 

![screenshot_20180330-192853](https://user-images.githubusercontent.com/1326949/38158916-575d704c-3452-11e8-9bfe-273ab377d805.png)
![img_4683](https://user-images.githubusercontent.com/1326949/38158917-5776aea4-3452-11e8-82d5-e8511c6c54dd.png)
![img_4682](https://user-images.githubusercontent.com/1326949/38158918-57902c4e-3452-11e8-96b6-07e69393b07b.png)

**Comment by frantic** [comment]
Have you started the server side part? The app depends on a few services that we have docker containers for. See [Local Setup](http://makeitopen.com/docs/en/1-A1-local-setup.html) instructions. Please reopen if that didn't help

**Comment by sumitsavla** [comment]
Yes, docker is running. Along with it parse server and Mongo. Parse dashboard is showing data as well. Just that Android app is giving error. When I Googled for this error, people had suggested to add following - https://github.com/parse-community/parse-server/issues/651 process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"

This actually worked once as well and Android app was showing data a week ago. Last weekend it stopped working. Also if u download LIVE f8 app from ios / Android app store that app gives same error as well
