### ISSUE TITLE
Parse Version will lead to app crash in iOS

### ISSUE THREAD

**Issue by terence612** [fbsamples/f8app#216]
Same problem in #215 
In the document by Parse
http://parseplatform.org/Parse-SDK-JS/api/v1.11.0/Parse.html#.setAsyncStorage
```
Call this method to set your AsyncStorage engine Starting Parse@1.11
```
However inside the package.json, parse is still in ^1.10.0,
and if we run 
```yarn upgrade```
that will lead to another problem, which is the YellowBox.js and moment dependencies.

In order to fix this, please set the version of parse in package.json to ^1.11.0.

**Comment by hrdzkj** [comment]
thinks. it works . but not data display. 
![Uploading image.png…]()

**Comment by terence612** [comment]
Mine works fine. Maybe try to launch the docker again.

**Comment by caabernathy** [comment]
Closing as the PR by @terence612  has been merged to resolve this.
