### ISSUE TITLE
makeitopen.com domain had expired

### ISSUE THREAD

**Issue by jianglinchun** [fbsamples/f8app#225]
The domain makeitopen.com has expired??

`Domain Name: makeitopen.com 
Registry Domain ID: 2017633140_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.markmonitor.com
Registrar URL: http://www.markmonitor.com
Updated Date: 2018-02-28T02:07:32-0800
Creation Date: 2016-03-31T09:12:52-0700
Registrar Registration Expiration Date: 2020-03-31T00:00:00-0700
Registrar: MarkMonitor, Inc.
Registrar IANA ID: 292
Reseller:
Domain Status: clientUpdateProhibited (https://www.icann.org/epp#clientUpdateProhibited)
Domain Status: clientTransferProhibited (https://www.icann.org/epp#clientTransferProhibited)
Domain Status: clientDeleteProhibited (https://www.icann.org/epp#clientDeleteProhibited)
Registrant State/Province: CA
Registrant Country: US
Name Server: b.ns.facebook.com
Name Server: a.ns.facebook.com
DNSSEC: unsigned
Registrar Abuse Contact Email: abusecomplaints@markmonitor.com
Registrar Abuse Contact Phone: +1.2083895740
URL of the ICANN WHOIS Data Problem Reporting System: http://wdprs.internic.net/
>>>Last update of WHOIS database: 2018-05-30T08:13:29Z <<<

For more information on Whois status codes, please visit https://icann.org/epp`

**Comment by caabernathy** [comment]
It looks set to expire in 2010 now.
