### ISSUE TITLE
Cannot find module 'http2'

### ISSUE THREAD

**Issue by Gitsanto** [fbsamples/f8app#226]
Parse Error occured during "yarn server" command.
module.js:491
parse_1            |     throw err;
parse_1            |     ^
parse_1            |
parse_1            | Error: Cannot find module 'http2'
parse_1            |     at Function.Module._resolveFilename (module.js:489:15)
parse_1            |     at Function.Module._load (module.js:439:25)
parse_1            |     at Module.require (module.js:517:17)
parse_1            |     at require (internal/module.js:11:18)
parse_1            |     at Object.<anonymous> (/usr/local/lib/node_modules/parse-server/node_modules/apn/index.js:15:15)
parse_1            |     at Module._compile (module.js:573:30)
parse_1            |     at Object.Module._extensions..js (module.js:584:10)
parse_1            |     at Module.load (module.js:507:32)
parse_1            |     at tryModuleLoad (module.js:470:12)
parse_1            |     at Function.Module._load (module.js:462:3)
f8app-master_parse_1 exited with code 1

**Comment by karlafalcao** [comment]
Hi, @Gitsanto try to change the Dockerfile inside server/parser/ upgrade the node version to `9.11-alpine`.

**Comment by davewthompson** [comment]
Also, don't forget to run _docker-compose build_ in the root directory of the project for the change to the Dockerfile to be committed.

**Comment by Gitsanto** [comment]
Thanks @karlafalcao and @davewthompson it worked for me.
