### ISSUE TITLE
Where is the RCTFBLikeView?

### ISSUE THREAD

**Issue by zh-wowtv** [fbsamples/f8app#23]
I got the error:

> Native component for "RCTFBLikeView" does not exist
> Native component for "RCTFBLoginButton" does not exist
>Native component for "RCTFBSendButton" does not exist
>Native component for "RCTFBShareButton" does not exist
>Native component for "BVLinearGradient" does not exist

Where are they? Thanks.

**Comment by frantic** [comment]
Is this iOS or Android version? This seems to be a warning, might be worth filing an issue against https://github.com/facebook/react-native-fbsdk

**Comment by justfornow1000** [comment]
Android version and thanks I'll do that ...

On Apr 25, 2016 1:47 PM, "Alexander Kotliarskyi" <notifications@github.com>
wrote:
>
> Is this iOS or Android version? This seems to be a warning, might be
worth filing an issue against https://github.com/facebook/react-native-fbsdk

**Comment by frantic** [comment]
👍

**Comment by justfornow1000** [comment]
I appreciate your help this is new to me so I could use some help all around the board of possible ?? Let me know at your earliest convenience.. Thank you.. J

**Comment by frantic** [comment]
According to https://github.com/facebook/react-native-fbsdk/blob/efb7470ba16d7828951ba48753d8be68c13b69cb/Android/src/main/java/com/facebook/reactnative/androidsdk/FBLikeViewManager.java#L38 the `RCTFBLikeView` should exist. Are you sure you `npm install`ed all dependencies?

**Comment by justfornow1000** [comment]
Yes it worked thank you so much if u ever need me lmk...

**Comment by justfornow1000** [comment]
No I don't  believe i did thanks ..

**Comment by stedda** [comment]
you should use `rnpm link` from facebook sdk to link the dependencies from react with those from android project. Restart the process and it should work.
