### ISSUE TITLE
RelayModernGraphQLTag:Expected an request,got...

### ISSUE THREAD

**Issue by EdworldWang** [fbsamples/f8app#231]
![1](https://user-images.githubusercontent.com/19811123/42813958-411331d4-89f5-11e8-8285-b54e7e932d96.jpg)
![2](https://user-images.githubusercontent.com/19811123/42813960-4178c86e-89f5-11e8-9025-a87bf90ed5e0.jpg)
accident happened when i launch my app;

**Comment by hefuweill** [comment]
本地服务器没搭建吧
