### ISSUE TITLE
npm run import-data returns error

### ISSUE THREAD

**Issue by arnorhaux** [fbsamples/f8app#24]
macbook:f8app xxxxx$ npm run import-data

> F8v2@0.0.1 import-data /Users/xxxxx/Documents/workspace/f8app
> babel-node ./scripts/import-data-from-parse.js

Loading Speakers
Cleaning old Speakers data
ParseError { code: undefined, message: 'unauthorized' }

Yes I have the local parse server running and local mongo instance up and running

**Comment by justfornow1000** [comment]
I could really use some help understanding this if I could please contact me if possible I would really appreciate it thank you .. If you are unable to help me would u please guide me in the right direction

**Comment by frantic** [comment]
Did you change any of the server configs (like `MASTER_KEY` or `APP_ID`)?

You can also try starting your Parse server using `VERBOSE=1 npm start` and check if it has any suspicious messages when you running the import script.

**Comment by justfornow1000** [comment]
OK yes i did and thank you
On Apr 25, 2016 3:54 PM, "Alexander Kotliarskyi" <notifications@github.com>
wrote:

Did you change any of the server configs (like MASTER_KEY or APP_ID)?

You can also try starting your Parse server using VERBOSE=1 npm start and
check if it has any suspicious messages when you running the import script.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/fbsamples/f8app/issues/24#issuecomment-214455541>

**Comment by justfornow1000** [comment]
OK yes i did and thank you

**Comment by arnorhaux** [comment]
Exuse me, I'm the one that opened this issue. I have not changed anything in the config files.

I took the http get request straight from the data import script and placed it to a curl command.

curl -X GET -H "X-Parse-Application-Id: R0yDMIKCUyEke2UiadcTBBGd1L5hMBTGJSdBNL3W" -H "X-Parse-JavaScript-Key: BJ5V0APFMlvmCBPDXl9Mgh3q3dFrs18XkQz6A2bO" https://api.parse.com/1/classes/Notification

this returns all the data but when when I use the import script it returns {"error":"unauthorized"}

* notice that I skipped the single qoutes around api keys and then it worked

This is probably due to how curl is handling single qoutes vs. double qoutes in various encoding (I'm using UTF-8)

**Comment by frantic** [comment]
@arnorhaux considering your logs

> Cleaning old Speakers data
>  {"error":"unauthorized"}

the error is coming from your local Parse server, not remote production one. Try accessing dashboard (see README) and check if it works.

**Comment by arnorhaux** [comment]
Hi

My bad, it was using process.env.MASTER_KEY variable which I had set for other instance of parse server on my workstation.

Thank you and great work !

**Comment by frantic** [comment]
Awesome, I'm glad it worked out! 👍
