### ISSUE TITLE
Unable to Facebook login

### ISSUE THREAD

**Issue by zh-wowtv** [fbsamples/f8app#25]
I clone your project but I can't login to Facebook.  To debug, I modified a bit in actions/login.js:

```
async function ParseFacebookLogin(scope): Promise {
  console.log('ParseFacebookLogin')
  return new Promise((resolve, reject) => {
    // Parse.FacebookUtils.logIn(scope, {
    //   success: resolve,
    //   error: (user, error) => reject(error && error.error || error),
    // });

    Parse.FacebookUtils.logIn(scope, {
            success: (user) => {
              if (!user.existed()) {
                alert("User signed up and logged in through Facebook!");
              } else {
                alert("User logged in through Facebook!");
              }
            },
            error: (user, error) => {
              alert("User cancelled the Facebook login or did not fully authorize.");
            }
          })
  });
}
```

The **Parse.FacebookUtils.logIn** **success** and **error** are not called at all. The only things I changed is the version of react-native and other corresponding package. I'm using react-native 0.25.rc-0.

Any idea? Thanks.

**Comment by frantic** [comment]
No idea, sorry. You can place a couple of breakpoints in FacebookSDK.js file to trace the login progress

**Comment by zh-wowtv** [comment]
It turns out I should add something in my AppDelegate.m.

**Comment by frantic** [comment]
What was that?

**Comment by justfornow1000** [comment]
What was what??

**Comment by frantic** [comment]
Oh I was wondering how did you resolve your problem?

**Comment by justfornow1000** [comment]
I haven't yet , I told you I had little to no knowledge with this that's
why I was asking for some assistance.. J

**Comment by nakulgan** [comment]
You need to hook react-native-fbsk correctly. You can follow the [Readme](https://github.com/facebook/react-native-fbsdk) and set it up with a Facebook app

**Comment by zh-wowtv** [comment]
@nakulgan Yes. You're right. I solved the issue already. It has nothing to do with parse.com. I came from Cordova I though everything will be setup like what Cordova did. Thanks.
