### ISSUE TITLE
Question about ParallaxBackground 

### ISSUE THREAD

**Issue by zh-wowtv** [fbsamples/f8app#27]
Is it possible to center the effect of the ParallaxBackground? I mean locate the background image center instead of top left corner.

Thanks

**Comment by frantic** [comment]
Yes, you can use flexbox to center the items ([example](https://philipwalton.github.io/solved-by-flexbox/demos/vertical-centering/)). You can also do it manually, there is [the width of the image](https://github.com/fbsamples/f8app/blob/master/js/common/ParallaxBackground.js#L97) and [the width of the screen](https://github.com/fbsamples/f8app/blob/master/js/common/ParallaxBackground.js#L39), from that point it's just math.

**Comment by zh-wowtv** [comment]
Actually what I mean is the anchor point of the image. I'm wondering if it's possible to setup the anchor point.
