### ISSUE TITLE
BUILD FAILED (ios)

### ISSUE THREAD

**Issue by thinkwing** [fbsamples/f8app#30]
my_path/f8app/node_modules/react-native-fbsdk/iOS/core/iOS/RCTFBSDKAccessToken.m:50:21: No known class method for selector 'refreshCurrentAccessToken:'

![screen shot 2016-04-30 at 3 04 59 am](https://cloud.githubusercontent.com/assets/368345/14926824/c7e9d61a-0e80-11e6-82af-8085f33c0a54.png)

Xcode: 7.3
node: 6.0.0
npm: 3.8.6
react-native-cli: 0.2.0
react-native: 0.23.1

**Comment by thinkwing** [comment]
Any ideas?

**Comment by frantic** [comment]
No ideas, sorry. Are you seeing this error when building this repo? Try removing all untracked files (`git clean -xfd`) and doing `pod install` again. Maybe the project is picking up FacebookSDK from another manually configured path?
