### ISSUE TITLE
Unable to run on ios simulator

### ISSUE THREAD

**Issue by patmisch** [fbsamples/f8app#32]
Builds fine, but then getting this error immediatly upon launch: 
![simulator screen shot apr 30 2016 3 03 06 pm](https://cloud.githubusercontent.com/assets/722715/14937998/b9aeffe4-0ee4-11e6-8b6d-b7fee62f527d.png)

Any ideas?

**Comment by thinkwing** [comment]
I have the same problem as you...

**Comment by frantic** [comment]
Seems like React Native version mismatch. Are you sure you are not running the packager from different folder?

**Comment by patmisch** [comment]
I absolutely was and didn't realize it. Thanks.
