### ISSUE TITLE
Parse + React SDK

### ISSUE THREAD

**Issue by shic** [fbsamples/f8app#33]
In the F8 development site wrote:
>http://makeitopen.com/tutorials/building-the-f8-app/data/
>Yep, because we’re using the Parse + React SDK (specifically the parse/react-native package in it), we have incredibly simple SDK access baked right in.

But I found the project is not imported Parse + React SDK, and no use of it. Why?

**Comment by frantic** [comment]
You are right, we are not using ParseReact, just plain Parse JS SDK (please report this problem via https://github.com/facebook/makeitopen/issues)

The reason we are not using ParseReact is Redux is covered here http://makeitopen.com/tutorials/building-the-f8-app/planning/#data-access-with-react-native
