### ISSUE TITLE
Should use or kill "RatingScreen" and "ThirdPartyNotices"

### ISSUE THREAD

**Issue by ericvicenti** [fbsamples/f8app#36]
We have two views registered in the navigator that do not seem to be used ever. Can we either remove them from the codebase or add them into the app?

https://github.com/fbsamples/f8app/search?utf8=%E2%9C%93&q=rate&type=Code
https://github.com/fbsamples/f8app/search?utf8=%E2%9C%93&q=notices&type=Code

Or am I missing something? Maybe it is possible to open these from a push notif?

**Comment by frantic** [comment]
RatingScreen is used [here](https://github.com/fbsamples/f8app/blob/master/js/tabs/notifications/F8NotificationsView.js#L141), ThirdPartyNotices is not used in OSS (but can we keep it?)
