### ISSUE TITLE
XMLHttpRequest failed: \"Unable to connect to the Parse API\"

### ISSUE THREAD

**Issue by bechr05** [fbsamples/f8app#39]
Every time I build iOS app, it work okay at the beginning. I get launch screen, then first animation but then I get red error screen.

![screenshot 2016-05-10 19 06 48](https://cloud.githubusercontent.com/assets/9628098/15155350/66635244-16e2-11e6-8a14-aeeaba3293b7.png)

![screenshot 2016-05-10 19 06 42](https://cloud.githubusercontent.com/assets/9628098/15155351/6667d1ca-16e2-11e6-9ac5-0cf934275b6e.png)

Anyone help?

**Comment by frantic** [comment]
Are you running the Parse server? Check README for instructions on how to set it up. If you are getting this error on device, check that your `env.js` file has the correct IP address.
