### ISSUE TITLE
Unable to connect to the Parse API

### ISSUE THREAD

**Issue by umpirsky** [fbsamples/f8app#4]
I was following setup [instructions](https://github.com/fbsamples/f8app#setup) from readme.

Both:

* Parse Dashboard: http://localhost:8080/dashboard
* GraphiQL: http://localhost:8080/graphql

work fine locally for me.

```
$ lsof -iTCP:27017 -sTCP:LISTEN
```

Outputs nothing and import fails with:

```
$ npm run import-data

> F8v2@0.0.1 import-data /home/umpirsky/Projects/f8app
> babel-node ./scripts/import-data-from-parse.js

Loading Speakers
Cleaning old Speakers data
ParseError {
  code: 100,
  message: 'XMLHttpRequest failed: "Unable to connect to the Parse API"' }
```

Seems like I am missing something or readme requires more detailed setup instructions.

**Comment by kennydee** [comment]
Are you sure Mongo is running ?
```
brew install mongo
mongod --config /usr/local/etc/mongod.conf
```

**Comment by umpirsky** [comment]
@kennydee Thanks for fast response, really appreciate it.

After running `mongod --config /etc/mongodb.conf` (should be added to readme) I got:

```
$ npm run import-data

> F8v2@0.0.1 import-data /home/umpirsky/Projects/f8app
> babel-node ./scripts/import-data-from-parse.js

Loading Speakers
{ [FetchError: request to https://api.parse.com/1/classes/Speakers failed, reason: getaddrinfo EAI_AGAIN api.parse.com:443]
  name: 'FetchError',
  message: 'request to https://api.parse.com/1/classes/Speakers failed, reason: getaddrinfo EAI_AGAIN api.parse.com:443',
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN' }
```

I guess `api.parse.com` should be replaced with localhost?

**Comment by kennydee** [comment]
Did mongo is running fine ?

If so, restart the `npm start` command
Make sure no error are spotted on the log of the `npm start` command
(if you have mongo access error, maybe you run the `export DATABASE_URI` command line. If so, reinitialize to something like `export DATABASE_URI=mongo://localhost:27017` )

Then, try to access to the parse server on `http://localhost:8080/dashboard/` to see if everything is fine, and you should now be able to launch the `npm run import-data`

**Comment by umpirsky** [comment]
@kennydee OK, works now, thanks. :+1: 

Not sure what was missing, looks like restarting the `npm start` helped.

**Comment by leiMsnow** [comment]
@kennydee thanks.

**Comment by duyue6002** [comment]
This doesn't work for me! same question! Help!
