### ISSUE TITLE
Parse Dashboard Push Function Not works on both iOS and Android Simulator.

### ISSUE THREAD

**Issue by parkmap** [fbsamples/f8app#40]
I tested this app both iOS and Android.

Everything seems to be working fine but the Parse Send New Push doesn't working.

are you guys working fine with Push function on testing?

what can i do for using Push??

**Comment by frantic** [comment]
Hi @parkmap, it's a matter of configuration that we didn't have time to cover in our docs, sorry. You can look at [parse-server/wiki/Push](https://github.com/ParsePlatform/parse-server/wiki/Push) for more details on how to configure the server side.
