### ISSUE TITLE
Slow background parallax

### ISSUE THREAD

**Issue by trompx** [fbsamples/f8app#41]
Hello,

For your info, I usually test apps on old phones to detect performance problems. 
On an iphone 4, the background parallax is very laggy (compared to other native app or other animations in the f8app).
On a nexus 7, the app is butterly smooth, but compared to the ios version, the header background height does not change.
I didn't have the time to dive into the code yet but I think there might be room for improvement there.

**Comment by jordwalke** [comment]
Curious - are you running in dev mode? Are you connected to the debugger?

**Comment by trompx** [comment]
Hello @jordwalke, not at all, to test the app I directly downloaded it from itunes/play stores, so I don't know if they are up to date. I'll do more tests when I'll start my next react native project.

**Comment by jordwalke** [comment]
I'd be curious to see what it's like running (JSC) entirely on the main thread. It's relatively easy to test this.
