### ISSUE TITLE
Build failed in react-native-push-notification:processReleaseResources

### ISSUE THREAD

**Issue by marczzio** [fbsamples/f8app#42]
Hi, Im new in react-native and I follow the installation f8app in [makeitopen.com](url).
everything is smooth before I tried to do `react-native run-android`. When I run that command, comes the error that I don't know. Here is the error log.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-push-notification:processReleaseResourc
es'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.E
xecException: Process 'command 'C:\Android\sdk\build-tools\23.0.2\aapt.exe'' fin
ished with non-zero exit value 1
```
FYI
I'm using Android SDK Build tools 23.0.2.

I hope you guys can help me with this, since I'm very interested in react-native.

Thank you

**Comment by frantic** [comment]
Sorry, I don't know what could be wrong here. I believe my `build.gradle` file requires build tools [23.0.1](https://github.com/fbsamples/f8app/blob/master/android/app/build.gradle#L79) (not sure it's causing the trouble, but worth a try).

You can also file an issue against [react-native-push-notification](https://github.com/zo0r/react-native-push-notification) repo.

**Comment by HubMahesh** [comment]
............................................................................................................................
............................................................. everything fine here..........................
But from here same problem. 

AAPT err(32591897): C:\Users\my\Desktop\reactivNative Projects\notificationTest\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.
gms\play-services-base\10.0.1\res\drawable-mdpi-v4\common_google_signin_btn_icon_dark_pressed.9.png ERROR: Unable to open PNG file
              
FAILURE: Build failed with an exception.
              
* What went wrong:
Execution failed for task ':react-native-push-notification:mergeReleaseResources'.
> Crunching Cruncher common_google_signin_btn_text_dark_normal.9.png failed, see logs
AAPT err(5790405): C:\Users\my\Desktop\reactivNative Projects\notificationTest\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.g
ms\play-services-base\10.0.1\res\drawable-mdpi-v4\common_google_signin_btn_text_dark_normal.9.png ERROR: Unable to open PNG file
AAPT err(5790405): C:\Users\my\Desktop\reactivNative Projects\notificationTest\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.g
ms\play-services-base\10.0.1\res\drawable-xhdpi-v4\common_google_signin_btn_text_dark_normal.9.png ERROR: Unable to open PNG file
              
AAPT err(5977832): C:\Users\my\Desktop\reactivNative Projects\notificationTest\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.g
ms\play-services-base\10.0.1\res\drawable-mdpi-v4\common_google_signin_btn_icon_light_pressed.9.png ERROR: Unable to open PNG file
* Try:        
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
              
BUILD FAILED  
              
Total time: 12.389 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html


Could't solve and know the issue, anyone faced and solve this issue. or any idea

**Comment by ericvillemure** [comment]
Same issue here
