### ISSUE TITLE
npm run import-data return error

### ISSUE THREAD

**Issue by hasanobss** [fbsamples/f8app#48]
$ npm run import-data

I have the local parse server running, return following; 

Loading Speakers
Cleaning old Speakers data
ParseError { code: 1, message: undefined }

**Comment by khanghoang** [comment]
@hasanobss what were `node` and `npm` version you used?

**Comment by smshuja** [comment]
I am getting the same error with the following versions.

node 5.1.0
npm 3.3.12

**Comment by hasanobss** [comment]
node 6.1.0
npm 3.8.6

**Comment by hasanobss** [comment]
I fixed it, problem was related install of parse-server which was not completed well. 
$ sudo npm install -g parse-server mongodb-runner 
$ mongodb-runner start

**Comment by veryitman** [comment]
@hasanobss 
I do it as you say. I get error:

error: Uncaught internal server error. { [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
  name: 'MongoError',
  message: 'connect ECONNREFUSED 127.0.0.1:27017' } Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:893:11)
    at exports._exceptionWithHostPort (util.js:916:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)

**Comment by veryitman** [comment]
@hasanobss Thank you.
