### ISSUE TITLE
import data throw error

### ISSUE THREAD

**Issue by beenhero** [fbsamples/f8app#50]
When run 'npm run import-data', it complains:

> ParseError {
>   code: 107,
>   message: 'Received an error with invalid JSON from Parse: <html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.10.0</center>\r\n</body>\r\n</html>\r\n' }

due to the basic authentication was added to https://api.parse.com/1/classes/***  endpoints, please make a work around, thanks.

**Comment by tychota** [comment]
It did get the same issue. It is pretty annoying ? Not possible to version the output of parse api ?

**Comment by maullerz** [comment]
same issue

**Comment by kilburn** [comment]
How did you work around the issue?

**Comment by divyenduz** [comment]
+1

**Comment by brucebnu** [comment]
+1  api.parse.api has shutdown.
