### ISSUE TITLE
Upgrade to new React-native version

### ISSUE THREAD

**Issue by zh-wowtv** [fbsamples/f8app#51]
I got the following error messages:

> Warning: ReactNative.createElement is deprecated. Use React.createElement from the 'react' package instead.

> Warning: ReactNative.cloneElement is deprecated. Use React.cloneElement from the 'react' package instead.

When I change the react-native to version:

> "react-native": "^0.25.0-rc"

What should I do? Thanks.

**Comment by frantic** [comment]
We should upgrade this project's RN version. Currently it's on `0.23`. `0.25` comes with a bunch of great performance improvements. I'll try to get to this within a week or two.

**Comment by zh-wowtv** [comment]
Great. Thanks.

**Comment by rozele** [comment]
If you can get to 0.26 or 0.27-rc, we could get the Windows stuff integrated here as well :-).

**Comment by zh-wowtv** [comment]
Any progress? Or can we help?

**Comment by zh-wowtv** [comment]
I think I can help to do the upgrading but when I run:

> react-native upgrade

Can't upgrade because **npm-shrinkwrap.json** is used. Any idea how can I unlock the version? Thanks.

**Comment by frantic** [comment]
Upgraded to RN 0.28
