### ISSUE TITLE
npm start failed !

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [fbsamples/f8app#54]
> F8v2@0.0.1 start /projects/f8app
> babel-node ./server/server.js

/projects/f8app/node_modules/babel-core/lib/transformation/file/index.js:556
      throw err;
      ^

SyntaxError: /projects/f8app/server/server.js: Unexpected token (85:2)
  83 |       users,
  84 |     }, IS_DEVELOPMENT),

> 85 |   );
>      |   ^
>   86 | }
>   87 |
>   88 | server.use(
>     at Parser.pp.raise (/projects/f8app/node_modules/babylon/index.js:1378:13)
>     at Parser.pp.unexpected (/projects/f8app/node_modules/babylon/index.js:2817:8)
>     at Parser.pp.parseExprAtom (/projects/f8app/node_modules/babylon/index.js:749:12)
>     at Parser.pp.parseExprSubscripts (/projects/f8app/node_modules/babylon/index.js:504:19)
>     at Parser.pp.parseMaybeUnary (/projects/f8app/node_modules/babylon/index.js:484:19)
>     at Parser.pp.parseExprOps (/projects/f8app/node_modules/babylon/index.js:415:19)
>     at Parser.pp.parseMaybeConditional (/projects/f8app/node_modules/babylon/index.js:397:19)
>     at Parser.pp.parseMaybeAssign (/projects/f8app/node_modules/babylon/index.js:360:19)
>     at Parser.pp.parseExprListItem (/projects/f8app/node_modules/babylon/index.js:1206:16)
>     at Parser.pp.parseCallExpressionArguments (/projects/f8app/node_modules/babylon/index.js:580:20)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! F8v2@0.0.1 start: `babel-node ./server/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the F8v2@0.0.1 start script 'babel-node ./server/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the F8v2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./server/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs F8v2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls F8v2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /projects/f8app/npm-debug.log

**Comment by hzhilt** [comment]
I have the same error,but I have not got the solution

**Comment by stevefermi** [comment]
I deleted the comma in after the 'IS_DEVELOPMENT'

and it seems that it works well.
