### ISSUE TITLE
errors during building ios

### ISSUE THREAD

**Issue by tonykaku** [fbsamples/f8app#57]
`/Users/TonyKaku/Sites/f8app/ios/Pods/FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKLikeButton.m:206:75: error: no
      known class method for selector 'viewControllerforView:'
                                 fromViewController:[FBSDKInternalUtility viewControllerforView:self]];
                                                                          ^~~~~~~~~~~~~~~~~~~~~
/Users/TonyKaku/Sites/f8app/ios/Pods/FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKLikeButton.m:213:75: error: no
      known class method for selector 'viewControllerforView:'
                                 fromViewController:[FBSDKInternalUtility viewControllerforView:self]];
                                                                          ^~~~~~~~~~~~~~~~~~~~~
2 errors generated.
`

**Comment by valinaga** [comment]
same for me... can't figure it out the issue.

**Comment by tonykaku** [comment]
Try pod update

**Comment by valinaga** [comment]
did the trick. thanks!

**Comment by hlung** [comment]
pod update doesn't work for me T_T

**Comment by omarojo** [comment]
+1

**Comment by nghiemdv** [comment]
You could change the name of the function to "viewControllerForView".

**Comment by thebeni** [comment]
In version 4.16.1 its named "viewControllerforView".
