### ISSUE TITLE
Problem to run Android version

### ISSUE THREAD

**Issue by zh-wowtv** [fbsamples/f8app#6]
Get the following error message after I click "x" in launch screen:

> undefined is not an object (evaluating 'map1.name')

> render
> F8MapView.js: 75

**Comment by frantic** [comment]
Please double-check if:

a. You are running the Parse/GraphQL servers (`npm start`)
b. The Android app can access your server (`adb reverse tcp:8080 tcp:8080`)'


Reopen if it doesn't work.
