### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by rbdoer** [fbsamples/f8app#64]
# $ pod install

Analyzing dependencies
Fetching podspec for `CodePush` from `../node_modules/react-native-code-push`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-fbsdkcore` from `../node_modules/react-native-fbsdk/iOS/core`
Fetching podspec for `react-native-fbsdklogin` from `../node_modules/react-native-fbsdk/iOS/login`
Fetching podspec for `react-native-fbsdkshare` from `../node_modules/react-native-fbsdk/iOS/share`
[!] Unable to find a specification for `FBSDKCoreKit` depended upon by `react-native-fbsdkcore`

when i run f8app, it  alert this error. how can i fix it ?
env:
osx:10.10
xcode:7.2.1
node:5.11.1

**Comment by chengmu** [comment]
same error here...

**Comment by antigirl** [comment]
sudo gem install cocoapods

**Comment by genehsun** [comment]
@antigirl can not help

**Comment by antigirl** [comment]
do you have cocoapods? see docs
```
CocoaPods (only for iOS)
Version 1.0+ recommended (gem install cocoapods --pre)```

**Comment by genehsun** [comment]
@antigirl thx

**Comment by RamyarIran** [comment]
any update about this issue ? unable to run because of this

**Comment by jerryjren** [comment]
same error. any update?

**Comment by deerW** [comment]
+1,any update?

**Comment by gaving** [comment]
Anybody get a solution for this one? Just can't build the project at all.

**Comment by gaving** [comment]
So it turns out this is a [breaking change](http://stackoverflow.com/a/21468667/126893) from an old cocoa pods install.

The below steps fixed my issue.

    mbp:~/Sandbox/f8app/ios% rm -rf ~/.cocoapods/
    /Users/gavin/.cocoapods//repos
    /Users/gavin/.cocoapods/
    mbp:~/Sandbox/f8app/ios% pod setup --verbose

    Setting up CocoaPods master repo

    Cloning spec repo `master` from `https://github.com/CocoaPods/Specs.git` (branch `master`)
      $ /usr/local/bin/git clone https://github.com/CocoaPods/Specs.git master --progress
      Cloning into 'master'...
      remote: Counting objects: 1226904, done.
      remote: Compressing objects: 100% (223/223), done.
      remote: Total 1226904 (delta 104), reused 35 (delta 35), pack-reused 1226638
      Receiving objects: 100% (1226904/1226904), 393.82 MiB | 1.82 MiB/s, done.
      Resolving deltas: 100% (595791/595791), done.
      Checking out files: 100% (151721/151721), done.
      $ /usr/local/bin/git checkout master
      Already on 'master'
      Your branch is up-to-date with 'origin/master'.
    Setup completed
    pod setup --verbose  380.90s user 43.98s system 89% cpu 7:53.21 total
    mbp:~/Sandbox/f8app/ios% pod install
    Analyzing dependencies
    Fetching podspec for `CodePush` from `../node_modules/react-native-code-push`
    Fetching podspec for `React` from `../node_modules/react-native`
    Fetching podspec for `Yoga` from `../node_modules/react-native/ReactCommon/yoga`
    Fetching podspec for `react-native-fbsdk` from `../node_modules/react-native-fbsdk/iOS`
    Downloading dependencies
    Installing Bolts (1.8.4)
    Installing CodePush (1.12.2)
    Installing FBSDKCoreKit (4.22.0)
    Installing FBSDKLoginKit (4.22.0)
    Installing FBSDKShareKit (4.22.0)
    Installing React (0.43.4)
    Installing Yoga (0.43.4.React)
    Installing react-native-fbsdk (0.3.0)
    Generating Pods project
    Integrating client project

    [!] Please close any current Xcode sessions and use `F8v2.xcworkspace` for this project from now on.
    Sending stats
    Pod installation complete! There are 14 dependencies from the Podfile and 8 total pods installed.

    [!] Automatically assigning platform ios with version 8.0 on target F8v2 because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
    pod install  6.40s user 6.06s system 5% cpu 3:46.67 total
