### ISSUE TITLE
Pods-F8v2-frameworks.sh: No such file or directory

### ISSUE THREAD

**Issue by xfnibuzd** [fbsamples/f8app#67]
/f8app/ios/Pods/Target Support Files/Pods-F8v2/Pods-F8v2-frameworks.sh: No such file or directory
Someone met this kind of situation？help

**Comment by xfnibuzd** [comment]
This question has bothered me for a long time --"/f8app/ios/Pods/Target Support Files/Pods-F8v2/Pods-F8v2-frameworks.sh: No such file or directory"

**Comment by davidneudorfer** [comment]
Same issue here.

**Comment by AlbertBoy** [comment]
Build Phases->Embed Pods Frameworks ->"${SRCROOT}/Pods/Target Support Files/Pods-F8v2/Pods-F8v2-frameworks.sh"  delete!!!That is OK!!!
