### ISSUE TITLE
failed to find Build Tools revision 23.0.2

### ISSUE THREAD

**Issue by trompx** [fbsamples/f8app#68]
Hello,

I am having hard time to run the f8 app. During android-run, I get the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-push-notification'.
   > failed to find Build Tools revision 23.0.2
```

In android/app/build.gradle, default is:
`buildToolsVersion "23.0.1"`

So I installed build Tools 23.0.2 instead but then I have 
`> failed to find Build Tools revision 23.0.1` ...

I even try to install both version, and set in build.gradle alteratively 23.0.1 and 23.0.2 but each time one cannot be found.

**Comment by trompx** [comment]
When trying to make things work, I installed many different things. After a vagrant destroy and reinstall everything, that error disappeared.

**Comment by yaoshanliang** [comment]
I had the same problem, how to solve that?
@trompx

**Comment by yohnz** [comment]
I had the same problem

**Comment by 38017032** [comment]
I had the same problem. Fixed by running project from Android Studio, it asks for installing the missing build tools version.
