### ISSUE TITLE
Module 0 is not a registered callable module

### ISSUE THREAD

**Issue by wangxinarhat** [fbsamples/f8app#71]
I just clone this project and run it on linux, occur this error:

![screenshot from 2016-06-13 16-03-23](https://cloud.githubusercontent.com/assets/14964925/16255492/e172831c-380f-11e6-8a44-41947a5ada64.png)

how can I fix it?

**Comment by ananddayalan** [comment]
@wangxinarhat I'm getting the same error. Did you find a solution?

**Comment by wangxinarhat** [comment]
@ananddayalan remains unsolved

**Comment by lenkavon** [comment]
corresponding discussion -> https://github.com/facebook/react-native/issues/7832

**Comment by dbof10** [comment]
I tried @lenkavon suggested solution but it didn't work for me. I'm getting the same issue.
