### ISSUE TITLE
How is this project using module aliases?

### ISSUE THREAD

**Issue by hedgerh** [fbsamples/f8app#72]
I can't figure out how this project is able to use aliases to import components, like: `var F8Navigator = require('F8Navigator')`, as opposed to `require('./F8Navigator')`.  Is it being done somewhere in the `ios`/`android` folders?

I wouldn't post an issue for this if it weren't a sample app, and I can't seem to get an answer, and would like to learn how it's being done.

**Comment by evollu** [comment]
i have the same question. Did you figure it out?

**Comment by hedgerh** [comment]
I did, actually.  The haste module system that comes with React Native does it.  To add a new alias, add the following to the top of a file:

```
/**
 * @providesModule F8Navigator
 * @flow
 **/
```

I'm not sure if the `@flow` part is necessary, but wanted to include it anyway.

Cheers.

**Comment by evollu** [comment]
okay. If I remember correctly, haste is recommended for facebook internal use. So I shouldn't use it in my project?

**Comment by evollu** [comment]
how do I have the haste module system up then?

**Comment by hedgerh** [comment]
Check the `.flowconfig` file of this project to see how it's set up.  It was already set up in my project, so I'm not sure if I did it myself or not.
