### ISSUE TITLE
F8Button error

### ISSUE THREAD

**Issue by leonardgithub** [fbsamples/f8app#74]
in the render() function in the LoginButton.js, this.props.style is null, and I got the below error when I run "react-native run-android": 
ExceptionsManager.js:56 Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `F8Button`.
Any solution?

**Comment by leonardgithub** [comment]
It seems LinearGradient can be wrapped inside the TouchableOpacity directly.

**Comment by ralberts** [comment]
I have the same issue :-(

**Comment by iacxin** [comment]
The same issue

**Comment by iacxin** [comment]
How to solve it.

**Comment by leonardgithub** [comment]
@iacxin in render() function of F8Button.js, I just modify it as below:
return (
      <TouchableOpacity
        accessibilityTraits="button"
        onPress={this.props.onPress}
        activeOpacity={0.8}
        style={[styles.container, this.props.style]}>
        <Text>{caption}</Text>
      </TouchableOpacity>
    );
