### ISSUE TITLE
Question: about require

### ISSUE THREAD

**Issue by leonardgithub** [fbsamples/f8app#77]
In js/F8Navigator.js, why will "var F8TabsView = require('F8TabsView');" be ok? 
Shouldn't it be "var F8TabsView = require('./tabs/F8TabsView');" ?

**Comment by grit96** [comment]
Each file has a comment at the top containing `@providesModule F8TabsView`. This allows you to require the file from anywhere in the project using `require('F8TabsView')` without worrying about relative paths. It's something that is provided by react through the [commoner](https://github.com/facebook/commoner) module.
