### ISSUE TITLE
Migrate to NavigationExperimental

### ISSUE THREAD

**Issue by mikelambert** [fbsamples/f8app#8]
F8 was built with the regular Navigator, but from https://github.com/ericvicenti/navigation-rfc/blob/master/Docs/NavigationOverview.md it says "Facebook is transitioning from Navigator to NavigationExperimental, which will be the supported navigation library going forward."

Currently, Redux+NavigationExperimental tutorials are quite sparse, so seeing a real-world beautiful use case like the redux-based f8 migrate would be a big help (to me, at least, and I suspect others as well).

It's possible NavigationExperimental isn't yet API-stable enough for a migration, but hopefully this can be a tracking issue for that migration (or the reasons not to migrate), as I'd be very interested in following along in either case.

**Comment by frantic** [comment]
Actually @ericvicenti was looking at it, but we haven't had chance to switch in time for F8. Will definitely consider.

**Comment by ericvicenti** [comment]
I have it half-done. I'll try to put a PR up this weekend for it

**Comment by DexSinis** [comment]
CompileC /Users/a000/Documents/XcodeWP/GitHub/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/FBSDKCoreKit.build/Objects-normal/x86_64/FBSDKDeviceViewControllerBase.o FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKDeviceViewControllerBase.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/F8v2.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/a000/Documents/XcodeWP/GitHub/f8app/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/F8v2.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

How can I fix it when I use react-native run-ios ?

**Comment by zh-wowtv** [comment]
Any progress already? Thanks.

**Comment by ask007java** [comment]
Same question, any progress ?

**Comment by chriswong929** [comment]
Any progress?

**Comment by pauloFernandes** [comment]
There is any progress on it? It would be **really** helpful
