### ISSUE TITLE
Can't login with Facebook account

### ISSUE THREAD

**Issue by rozele** [fbsamples/f8app#81]
Getting an exception when logging in to Facebook here:
https://github.com/fbsamples/f8app/blob/master/js/actions/schedule.js#L103

It results in an exception on the local Parse service:
Uncaught internal server error. TypeError: Cannot read property 'type' of undefined
    at C:\src\f8app\node_modules\parse-server\lib\Controllers\DatabaseController.js:134:10

I submitted a PR against parse-server:
https://github.com/ParsePlatform/parse-server/pull/2114

Perhaps there is a client-side work around to pre-declare the type of the 'mySchedule' relation?

**Comment by valinaga** [comment]
mee to, having same issue. any idea of a fix?

**Comment by rajbala398** [comment]
I am also have the same issue

error: Uncaught internal server error. [TypeError: Cannot read property 'type' of undefined] TypeError: Cannot read property 'type' of undefined
    at /Users/x/parse/beenstack/node_modules/parse-server/lib/Controllers/DatabaseController.js:134:10
    at run (/Users/x/parse/beenstack/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /Users/x/parse/beenstack/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/Users/x/parse/beenstack/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:415:9)

**Comment by rozele** [comment]
A quick fix is to manually make the change to parse-server from this PR https://github.com/ParsePlatform/parse-server/pull/2114.  I still need to create a unit test to get them to accept the PR.

**Comment by georgi-kovachev** [comment]
I have same issue

**Comment by datamaker** [comment]
I solved this by trying. and, I think the problem parse server
1. node Version : I'm version 6.6.0 
2. git fetch --all && git reset --hard 78233d5 ( It's commit ID )
3. babel build
this is package.json 
    "clean": "rm -rf build && mkdir build",
    "build-css": "node-sass scss/app.scss public/css/app.css",
    "build-server": "babel -d ./build ./server -s",
    "build": "npm run clean && npm run build-css && npm run build-server",
4. forever runing

note. grpc error : just 'npm install grpc'
