### ISSUE TITLE
No podspec found for `react-native-fbsdk`

### ISSUE THREAD

**Issue by vnshgrg** [fbsamples/f8app#83]
I've been trying to run 'pod install' and every time I get the same error
`[!] No podspec found for 'react-native-fbsdk' in '../node_modules/react-native-fbsdk/iOS'`

**Comment by roselind** [comment]
Me too.
[!] No podspec found for `react-native-fbsdk` in `../node_modules/react-native-fbsdk/iOS`

**Comment by raineroviir** [comment]
Please refer to https://github.com/fbsamples/f8app/issues/80 for steps to solve the bug
