### ISSUE TITLE
[!] No podspec found for `react-native-fbsdk` in `../node_modules/react-native-fbsdk/iOS`

### ISSUE THREAD

**Issue by lee-my** [fbsamples/f8app#86]
when  cd ios; pod install 
[!] No podspec found for `react-native-fbsdk` in `../node_modules/react-native-fbsdk/iOS`

**Comment by santiwst** [comment]
it can be fixed by running the following comamnd:
```
$ npm install react-native-fbsdk
```

**Comment by valinaga** [comment]
same thing happens to me.
react-native v0.28
tried 
$ npm install react-native-fbsdk 
with no success
same error here:
[!] No podspec found for `react-native-fbsdk` in `../node_modules/react-native-fbsdk/iOS`

any ideas?

**Comment by frantic** [comment]
This was a problem with [`react-native-fbsdk`](https://github.com/facebook/react-native-fbsdk), the podspec was missing. Should be fixed now, I'll upgrade package.json soon.
