### ISSUE TITLE
All component gets rendered even if we required to render only one. 

### ISSUE THREAD

**Issue by naveensingh-daffodil** [fbsamples/f8app#87]
I'm not sure it is default behaviour or redux or something else but i found that on dispatching an action, this action traverse through all reducers(that's ok) but it also invoke the connect listener of every reducer that further resulting rendering of its component. This means on every dispatch, all component inside app state tree get rendered. Is this intentionally done by redux or i've done something wronge.
Help me out to clarify this things.

**Comment by frantic** [comment]
@naveensingh-daffodil maybe ask in http://www.reactiflux.com/? Theoretically redux-connect should not re-render the component if the connected props haven't changed.

**Comment by naveensingh-daffodil** [comment]
yeah @frantic u r right... once action is dispatched all the connect listen it & if they found any props changed only in this case corresponding component gets rendered
