### ISSUE TITLE
No visible @interface for 'RCTScrollView' declares the selector 'addScrollListener:'

### ISSUE THREAD

**Issue by vnshgrg** [fbsamples/f8app#89]
`No visible @interface for 'RCTScrollView' declares the selector 'addScrollListener:'`

While trying to run the app xCode gives the above error on `F8Scrolling.m` on `Line 54` and `Line 66`

**Comment by MathieuDoyon** [comment]
@vnshgrg do you find solution for this issue, I got the same error.

**Comment by frantic** [comment]
What's your Xcode version? I assume you followed `npm install` and `pod install`, and they succeeded?
