### ISSUE TITLE
Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/F8v2.app/Info.plist

### ISSUE THREAD

**Issue by mathjoy** [fbsamples/f8app#90]
Print: Entry, ":CFBundleIdentifier", Does Not Exist

I run pos install successfully:
pod install
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:140: warning: Insecure world writable dir /Users/georgehu/Library in PATH, mode 040777
Analyzing dependencies
Fetching podspec for `CodePush` from `../node_modules/react-native-code-push`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-fbsdk` from `../node_modules/react-native-fbsdk/iOS`
Downloading dependencies
Using Bolts (1.7.0)
Using CodePush (1.12.2)
Using FBSDKCoreKit (4.10.1)
Using FBSDKLoginKit (4.10.1)
Using FBSDKShareKit (4.10.1)
Using React (0.28.0)
Using react-native-fbsdk (0.2.2)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 13 dependencies from the Podfile and 7 total pods installed

**Comment by lee-my** [comment]
me too

**Comment by jypblue** [comment]
重新安装react-native-fbsdk即可，在f8app目录，重新安装npm install react-native-fbsdk

**Comment by jypblue** [comment]
`react-native upgrade`

**Comment by lee-my** [comment]
react-native upgrade
no use,why

**Comment by huchenme** [comment]
+1

**Comment by dstnation** [comment]
maybe this problem
check, have a "react-native-fbsdk.podspec" file in ./node_modules/react-native-fbsdk/iOS/

if doesn't have it
**download** directly [react-native-fbsdk.podspec](https://raw.githubusercontent.com/fbsamples/f8app/master/node_modules/react-native-fbsdk/iOS/react-native-fbsdk.podspec) into "./node_modules/react-native-fbsdk/iOS/"

then, remove pod.lock
then, pod install

**Comment by dstnation** [comment]
maybe same; 

> #95

**Comment by mathjoy** [comment]
I have to remove react-native-fbsdk   //const {AppEventsLogger} = require('react-native-fbsdk');
to make this app working.  It worked after clean react-native-fbsdk package.

Following files are need to change to math this requirement:

//const {AppEventsLogger} = require('react-native-fbsdk');
//AppEventsLogger.logEvent('Share Session', 1, {id});

  //AppEventsLogger.logEvent('Invite Friends', 1);
    //AppInviteDialog.show({
    //  applinkUrl: this.props.appLinkURL,
    //  previewImageUrl: this.props.appInvitePreviewImageURL,
    //}).catch((error) => {
    //  if (error.message) {
    //    alert(error.message);
    //  }
    //});

//module.exports = FacebookSDK;



       modified:   README.md
        modified:   ios/F8v2.xcodeproj/project.pbxproj
        modified:   ios/F8v2/AppDelegate.m
        modified:   ios/F8v2/Base.lproj/LaunchScreen.xib
        modified:   ios/PodFile
        modified:   ios/Podfile.lock
        modified:   js/FacebookSDK.js
        modified:   js/actions/login.js
        modified:   js/actions/schedule.js
        modified:   js/env.js
        modified:   js/setup.js
        modified:   js/store/track.js
        modified:   js/tabs/schedule/InviteFriendsButton.js
        modified:   js/tabs/schedule/SessionsCarousel.js
        modified:   node_modules/react-native-fbsdk/iOS/react-native-fbsdk.podspec
        modified:   package.json
        modified:   scripts/import-data-from-parse.js
        modified:   server/server.js

**Comment by mathjoy** [comment]
//FacebookSDK.init();
  //Parse.FacebookUtils.init();

**Comment by mathjoy** [comment]
//var FacebookSDK = require('FacebookSDK');

**Comment by frantic** [comment]
This was a problem with [`react-native-fbsdk`](https://github.com/facebook/react-native-fbsdk), the podspec was missing. Should be fixed now, I'll upgrade package.json soon.

**Comment by chaintan17** [comment]
@frantic i still have this problem

**Comment by jiazil** [comment]
@frantic i still have this problem

**Comment by Luckygirlllll** [comment]
the same error, how to fix it?
