### ISSUE TITLE
native module cannot be null

### ISSUE THREAD

**Issue by wxb2939** [fbsamples/f8app#91]
** BUILD SUCCEEDED ** but display native module cannot be null

**Comment by Shangyunliang** [comment]
+1 我也遇到了这个问题。

**Comment by luojf945** [comment]
我也遇到这个问题了，正在病急乱投医。看系统要求，推荐xcode7.3+，我用的是xcode7.2。怀疑跟这个有关系，正在下载最新版xcode。请问你的xcode版本是多少呢？

**Comment by luojf945** [comment]
。。。。更新至xcode7.3，还是同样的问题！！！！

**Comment by stovmascript** [comment]
Please speak English on GitHub!

**Comment by Shangyunliang** [comment]
+1 I have the same question !  YES ! We should speak English on GitHub !

**Comment by Shangyunliang** [comment]
i work it ok ! https://github.com/fbsamples/f8app/issues/92. Good Luck !
