### ISSUE TITLE
NotFoundError: Cannot find entry file global code@http://localhost:8081/index.ios.js in any of the roots: ["/Users/Mac/study/react_native/f8app"]     at DependencyGraph._getAbsolutePath (/Users/Mac/study/react_native/f8app/node_modules/node-haste/lib/index.js:288:13)     at /Users/Mac/study/react_native/f8app/node_modules/node-haste/lib/index.js:226:30     at process._tickCallback (internal/process/next_tick.js:103:7)

### ISSUE THREAD

**Issue by Shangyunliang** [fbsamples/f8app#92]
NotFoundError: Cannot find entry file global code@http://localhost:8081/index.ios.js in any of the roots: ["/Users/Mac/study/react_native/f8app"]
    at DependencyGraph._getAbsolutePath (/Users/Mac/study/react_native/f8app/node_modules/node-haste/lib/index.js:288:13)
    at /Users/Mac/study/react_native/f8app/node_modules/node-haste/lib/index.js:226:30
    at process._tickCallback (internal/process/next_tick.js:103:7)

I hope you can help me handle this problem. thank you very much .by the way。the screen was full of
red and native  module can not be null

**Comment by gonzochic** [comment]
+1

**Comment by luojf945** [comment]
+1

**Comment by Shangyunliang** [comment]
i don't no why. i delete all . and do it again. i work !  but i think this can help you: 
 "gem install cocoapods --pre". 

`MacBook-Pro:f8app SYL-PC$ node -v
v6.1.0
MacBook-Pro:f8app SYL-PC$ npm -v
3.8.6
MacBook-Pro:f8app SYL-PC$ pod --version
1.1.0.beta.1`

By the way i didn't execute " react-native upgrade"  

and i also have the question:
[!] No podspec found for `react-native-fbsdk` in `../node_modules/react-native-fbsdk/iOS`

but this can fix it:
MacBook-Pro:f8app SYL-PC$ sudo npm install react-native-fbsdk
F8v2@0.0.1 /Users/SYL-PC/study/rnwork/f8app
└── react-native-fbsdk@0.2.2 

ok. I hope this can help you if you can understand what i say. i am totally not good at English !!!!!

but I try my best to learn English well.
