### ISSUE TITLE
Need some advices on es6 Javascript in server

### ISSUE THREAD

**Issue by zh-wowtv** [fbsamples/f8app#93]
I have some problems to deploy my server to Openshift because of the JS es6 although I can run it in my aws ec2 instance by manually installing parse server. It seems the es6 can only be started by using nodemon which can't be run in Openshift. The other question is whether it will be slower a bit if I run es6 because it will be compiled to normal JS at run-time?

**Comment by frantic** [comment]
Sorry, this is outside of the scope of the F8 app. The server code is transformed on-the-fly using babel, make sure you use `npm start` as your command, not `node server/index.js`
