### ISSUE TITLE
native  module cannot be null

### ISSUE THREAD

**Issue by cgf120** [fbsamples/f8app#94]
i download this project  ，After I download the program, the environment according to the installation of the introduction said later, perform npm start
npm run import-data, then the react - native run - iOS installed successfully, but after loading the welcome page appears native Module can not be null

and the server get 
   NotFoundError: Cannot find entry file global code@http://localhost:8081/index.ios.js in any of the roots: ["/Users/cuigaofeng/Desktop/f8app"]
    at DependencyGraph._getAbsolutePath (/Users/cuigaofeng/Desktop/f8app/node_modules/node-haste/lib/index.js:288:13)
    at /Users/cuigaofeng/Desktop/f8app/node_modules/node-haste/lib/index.js:226:30
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by frantic** [comment]
1. Check if another instance of packager is running from a different folder
2. Did `npm install` and `pod install` succeed? Did you run the `.xcworkspace` (not `.xcodeproj`)?
