### ISSUE TITLE
(react-native run-android) undefined is not a function(evaluating 'StatusBarIOS.setStyle('default')')

### ISSUE THREAD

**Issue by tungh** [fbsamples/f8app#98]
react-native run-android

Same here！

undefined is not a function(evaluating 'StatusBarIOS.setStyle('default')')

**Comment by guochong** [comment]
same problem

**Comment by yuzhewo** [comment]
The solution to this problem is here https://github.com/fbsamples/f8app/issues/85#issuecomment-230150517
